### ISSUE TITLE
Change http url for crosswire

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#10]
Line 117:
`        http://www.bibletechnologies.net/osisCore.2.1.1.xsd">`
May be change to:
`        http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd">`

**Comment by adyeths** [comment]
Changing the schema location to point to a customized version used by a single organization is not appropriate. If there is ever a newer official version of the schema, then I will make the appropriate changes at that time.
