### ISSUE TITLE
Verse ranges with alpha-numeric low/high value

### ISSUE THREAD

**Issue by mmartin9684-sil** [adyeths/u2o#100]
If a verse range is used for the verse number, and the low or high verse in the verse range is not purely numeric (e.g., "\v 1-2a"), the _verserange_ method is not able to correctly generate the verse range list.  An exception is raised; e.g.,

"ValueError: invalid literal for int() with base 10: '2a'

**Comment by adyeths** [comment]
I will need to research this more. I'm not quite sure how to proceed with handling this situation.

**Comment by adyeths** [comment]
Research wasn't needed after all... this should be fixed now. (at least for verse ranges that start or end with an `a` or  `b` anyway. If more complexity is needed then I will have to revisit this.)
