### ISSUE TITLE
Out of range error during postprocessing

### ISSUE THREAD

**Issue by mmartin9684-sil** [adyeths/u2o#101]
The _postprocess_ method will throw an exception (line 2768, IndexError: list index out of range) if the last generated OSIS line matches "<lb type="x-p">.  When the script checks the content of the next generated line ('line[i + 1] == "</lg>"), it needs to check that there **is** a next line.

Sample USFM text:
\id FRT - Achi de Cubulco NT [acrC] -Guatemala 2009 (DBL 2015)
\toc1 I ʼUtz Laj Tzij Re I Dios
\rem *************** Title Page
\mt1 I ʼUtz Laj Tzij Re I Dios
\b
\pc El Nuevo Testamento en el idioma Achí de Cubulco de Guatemala
\pc [acrC]
\b
\pc Traducción: © 2009, Wycliffe Bible Translators, Inc.
\b
\pc Primera edición: 1984, Sociedad Bíblica Internacional
\b
\pc Segunda edición: 2009, Wycliffe Bible Translators
\b
\pc Edición para la Web
\pc 2015, Wycliffe Bible Translators, Inc.
\pc www.Wycliffe.org
\b

**Comment by adyeths** [comment]
This is now fixed.

**Comment by mmartin9684-sil** [comment]
Fantastic, thanks!
