### ISSUE TITLE
Poetry markup (\q1, \q2) results in invalid OSIS output

### ISSUE THREAD

**Issue by mmartin9684-sil** [adyeths/u2o#103]
Poetry markup (e.g., "\q2 <text>") results in invalid OSIS output.
(Note also that the closing ("\cls <text>") and signature ("\sig <text>") is not included in the OSIS output.

- Sample USFM:
[test-usfm-input.txt](https://github.com/adyeths/u2o/files/4061991/test-usfm-input.txt)

- OSIS output:

[test-osis-output.txt](https://github.com/adyeths/u2o/files/4061989/test-osis-output.txt)

- Error:
xml.etree.ElementTree.ParseError: mismatched tag

**Comment by adyeths** [comment]
This was a problem with processing \cls tags in relation to marking the end of verses. It's fixed now.

**Comment by mmartin9684-sil** [comment]
Thanks again Ryan!
