### ISSUE TITLE
Relaxed conformance option?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#106]
I was recently notified that **JohnAustinDev** had updated `usfm2osis.pl` in `refdoc/Module-tools` to permit using `\xt_...\xt*` anywhere in the text, not just within cross reference notes.

Might this also be something to consider for `u2o.py` ?

Are there any further aspects under **Relaxed conformance** that might be of interest?

**Comment by DavidHaslam** [comment]
Sorry, path was misremembered.


[Scripts and tools for SWORD module conversions] (https://github.com/refdoc/Module-tools)

**Comment by adyeths** [comment]
Unless I'm mistaken, `\xt ...\xt*` isn't supposed to be used outside of cross reference notes in USFM.

**Comment by DavidHaslam** [comment]
I have it on good authority from Jeff Klassen at UBS ICAP that it may be used “almost anywhere”.

It’s conceivable that the documentation for USFM 3.x still lags behind what is permissible *de facto* in **Paratext 9**.

We should bear in mind that USFM evolves to meet needs that arise in new situations.

btw. My enquiry about USFM was in regard to how one might make verse numbers in “chapter summaries” act as links that would jump to the actual verse below when clicked.

cf. Many editions even of the KJV were printed with such italicised chapter summaries in smaller font size, centrally aligned in the column.

**Comment by cmahte** [comment]
See the first example after the word Attributes below the \xt heading. 

https://ubsicap.github.io/usfm/notes_basic/xrefs.html

This is new behavior in USFM 3. 

Also note that it has pipe |  functionality added (new in USFM 3.0) This allows the link to be on words or numbers.

**Comment by adyeths** [comment]
Ah yes... I will see what I can do to address this particular situation.

**Comment by adyeths** [comment]
closing this issue because u2o already handles \xt tags outside of crossreferences.
