### ISSUE TITLE
Still some issues with notes and \fp tag

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#11]
osis2mod, gave me this error:
`WARNING(NESTING): verse Matt.25.29 is not well formed:(3,4)`
`WARNING(NESTING): verse Rom.9.6 is not well formed:(5,6)`
`WARNING(NESTING): verse Gal.3.12 is not well formed:(6,7)`
`WARNING(NESTING): verse Eph.1.14 is not well formed:(7,8)`
`WARNING(NESTING): verse Phil.1.2 is not well formed:(9,8)`
When I look in the osis, I found this new issues:
`<verse sID="Gal.3.12" osisID="Gal.3.12" n="12" />Luyalu ya bansiku ya Moyize, yo ke kwendila ata fioti ve ti Luyalu ya lukwikilu, sambu Luyalu ya bansiku ke kwendila kumosi ti ngindu ya bo sonikaka nde : <hi type="italic">Muntu ya ke lungisa bansiku yina, yandi ta zinga na nzila na yo.</hi><note placement="foot">Na v. 12 Ndinga  ... ndola ti lufwa. </div><div type="paragraph">Na v. 13 Ndinga yai... bansumuki.</div></note>`
You can see the lack of one `<div>` marker.
All the issues report by osis2mod are the same, a lake of a marker for the fp tag. Still with Eph 1.14:
`<verse sID="Eph.1.14" osisID="Eph.1.14" n="14" />Mpeve ...Nzambi.<note placement="foot">Na v. 14, beto ke kembila lukumu ... ya mvimba.</div></note>`

**Comment by adyeths** [comment]
I'm not sure I will be able to fix this particular issue without access to a usfm source document where it shows up.

**Comment by adyeths** [comment]
I made some changes to try and fix this problem. If the changes worked then I will close this issue. If not, then I will need to see some example usfm source demonstrating this issue in order to resolve it.

**Comment by LAfricain** [comment]
Wonderful! It runs perfectly! A very big thank you!!
