### ISSUE TITLE
Add support for jmp

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#112]
Hello,
For now, if I have entries with \jmp it's not processed.

**Comment by adyeths** [comment]
u2o should do *something* with the tag. Not what is ideal, though. It should be converting it to a seg tag. If it's not doing *anything* with it, then I'd need to see the source so I can adjust the script to handle it. (Properly processing this tag is likely beyond my abilities.)

**Comment by LAfricain** [comment]
Hi,
Two example of tags:
```
Gardez-vous de mépriser un seul de ces petits » (Mt. 18,10) : mais réservons le surplus pour cet endroit\f + \ft \+jmp Livre VIII,57 sqq.|link-href="LUK 16:16-18"\+jmp*\f*.\jmp link-href="prj:CAM LUK 16:16-18"\jmp*
```

**Comment by adyeths** [comment]
I may be wrong, but it looks to me like you're trying to use jmp tags for cross references here.

**Comment by adyeths** [comment]
Also, the 2nd example doesn't seem to follow the syntax for the jmp tag.

**Comment by adyeths** [comment]
the bug that prevented processing of jmp tags has been fixed.
