### ISSUE TITLE
Add support for lemma

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#117]
Hi,
It is possible that some bibles use the lemma marker. For example for an interlinear text. But during export this marker is ignored. Would it be possible to integrate it correctly into the output osis file? For example:
If I have an usfm file like this: `\w Βίβλος|strong="G976" lemma="Livre" x-morph="N-NFS"\w*` I woul like an output like this:
` <w lemma="strong:G976 lemma:Livre" morph="robinson:N-NSF">Βίβλος</w>`

Thank you!

**Comment by adyeths** [comment]
The lemma attribute should already be properly converted. The bug preventing it from being converted when strongs numbers were present has already been fixed.

**Comment by LAfricain** [comment]
In fact the output usfm `lemma="[This is the] record"` is processed. But I have: `<index index="Glossary" level1="[This is the] record" />` but to display the lemmas in xiphos for example, I would need either `lemma="[This is the] record"` or after strong
 `lemma="strong:G976 lemma:[This is the] record"`

**Comment by adyeths** [comment]
Should be fixed now.

**Comment by LAfricain** [comment]
I'm really sorry! I took as example tischendorfmorph.OSIS.xml, but this template seems wrong. lemma seems to be separated from strong. If not, it's displayed all the time in the gui. I'll investigate more and I'll come back, but the good way to write lemma seems to be:
`lemma="[This is the] record"`

**Comment by DavidHaslam** [comment]
@LAfricain 

Can this issue now be closed?
