### ISSUE TITLE
"WARNING(NESTING): verse Gen.2.10 is not well formed" with list items

### ISSUE THREAD

**Issue by Screwtapello** [adyeths/u2o#118]
I am trying to learn about OSIS and SWORD modules by converting the USFM version of the [Berean Standard Bible](https://berean.bible/downloads.htm) using this converter.

In Genesis 2:10-14, the USFM marks each river as a list item. Here's a minimal example:

```usfm
\id GEN - Berean Study Bible
\mt1 Genesis
\c 2
\v 10 Now a river flowed out of Eden to water the garden, and from there it branched into four headwaters: 
\b
\li1 
\v 11 The name of the first river is Pishon; it winds through the whole land of Havilah, where there is gold. 
```

Converting this snippet to OSIS with the latest version (81cfcf3839182a77a0828007c035e2cb6db9efc8) of this tool, I get the following OSIS document:

```xml
<?xml version='1.0' encoding='utf-8'?>
<osis xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace http://www.bibletechnologies.net/osisCore.2.1.1.xsd">
  <osisText osisIDWork="BSBusfm" osisRefWork="Bible" xml:lang="en">
    <header>
      <revisionDesc resp="st">
        <date>2023.06.05T21.58.24</date>
        <p>Converted from USFM source using u2o.py</p>
      </revisionDesc>
      <work osisWork="BSBusfm">
        <title>BSBusfm</title>
        <description type="usfm" subType="x-id">GEN - Berean Study Bible</description>
        <type type="OSIS">Bible</type>
        <identifier type="OSIS">Bible.en.BSBusfm</identifier>
        <refSystem>Bible</refSystem>
      </work>
    </header>
    <div type="book" osisID="Gen" canonical="true"><!-- mt1 --><title level="1" type="main">Genesis</title><chapter sID="Gen.2" osisID="Gen.2" n="2"/><verse sID="Gen.2.10" osisID="Gen.2.10" n="10"/>Now a river flowed out of Eden to water the garden, and from there it branched into four headwaters: <list><item type="x-indent-1"><verse eID="Gen.2.10"/><verse sID="Gen.2.11" osisID="Gen.2.11" n="11"/>The name of the first river is Pishon; it winds through the whole land of Havilah, where there is gold. <verse eID="Gen.2.11"/></item></list><chapter eID="Gen.2"/></div>
  </osisText>
</osis>
```

I can clean that up a bit to highlight the XML structure a little better:

```xml
<?xml version='1.0' encoding='utf-8'?>
<osis xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace http://www.bibletechnologies.net/osisCore.2.1.1.xsd">
  <osisText osisIDWork="BSBusfm" osisRefWork="Bible" xml:lang="en">
    <header></header>
    <div type="book" osisID="Gen" canonical="true">
        <chapter sID="Gen.2" osisID="Gen.2" n="2"/>
            <verse sID="Gen.2.10" osisID="Gen.2.10" n="10"/>Now a river flowed out of Eden to water the garden, and from there it branched into four headwaters:
            <list>
                <item type="x-indent-1"><verse eID="Gen.2.10"/><verse sID="Gen.2.11" osisID="Gen.2.11" n="11"/>The name of the first river is Pishon; it winds through the whole land of Havilah, where there is gold. <verse eID="Gen.2.11"/></item>
            </list>
        <chapter eID="Gen.2"/>
    </div>
  </osisText>
</osis>
```

As I understand it, verse 10 starts outside the list, and then ends immediately inside the first list item, just before verse 11 starts. That seems reasonable to me, especially as a translation of the above USFM, but `osis2mod` complains:

```
You are running osis2mod: $Rev: 3769 $ (SWORD: 1.9.0)
WARNING(NESTING): verse Gen.2.10 is not well formed:(3,5)
SUCCESS: osis2mod: has finished its work and will now rest
```

It would be convenient if verse-ending milestones at the very beginning of the inside of a markup structure could be moved to the outside, but I don't know how practical that would be to do. Alternatively, it would be interesting to know what the USFM markup for verses in list items *should* look like.

Interestingly, in the full version of the text, all the items in verses 10-14 begin with a milestone for the end of the previous verse, but `osis2mod` only complains about verse 10. I'm not sure why.

**Comment by adyeths** [comment]
It's a bit challenging to get verse end markers in a sensible place. I will see what I can do here though because this seems to be something that should definitely be corrected.

**Comment by adyeths** [comment]
Just updated postprocessing of verse end markers. should be more sensible now.

Note that I found a missing space between the usfm verse marker in Ephesians 3:14 and the "..." immediately following it. Adding a space immediately after the number allows for the usfm to validate. I sent an email reporting it.

**Comment by Screwtapello** [comment]
I can confirm the problem is fixed, thanks!
