### ISSUE TITLE
the way \fp tags are handled does not validate

### ISSUE THREAD

**Issue by adyeths** [adyeths/u2o#12]
Since p tags cannot be nested in osis, I chose to use div tags with a type of "paragraph" inside footnotes when usfm \fp tags are present. However, according to the osis schema, div tags are not allowed inside note tags. So the osis markup that is generated when usfm \fp tags are present will not validate.

**Comment by DavidHaslam** [comment]
Given the rare occurrence of `\fp` and although perhaps it goes against the grain for OSIS philosophy, isn't this one of those situations where simply using a line break within the note element would suffice as an easy solution?

i.e. Forget paragraphs and divisions in the context of note elements, and simply convert `\fp` to `<lb/>`.

I think there would be no objections from those that use OSIS to make SWORD modules.

**Comment by adyeths** [comment]
No, using a line break where a paragraph break belongs is not appropriate. I already know what needs to be done, and when I get time I will fix this problem. This issue was created simply as a reminder that the current behavior is broken.
