### ISSUE TITLE
Missing EOLs

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#120]
While I was helping Fr Cyrille on a CrossWire project, I discovered that the OSIS XML file that he made using `u2o.py` did not have the expected EOLs after most chapter and verse **eID** elements.

See [https://gitlab.com/crosswire-bible-society/ukogienko/-/issues/3](https://gitlab.com/crosswire-bible-society/ukogienko/-/issues/3)

For various reasons, it's a few years since I myself last used `u2o.py` but I'm pretty certain this did not use to be the case.

Was this change intended, or is it due to a bug in your program?

**Comment by adyeths** [comment]
This is expected behavior. I'm not sure why there are supposed to be EOLs after chapter and verse eID elements. If you don't want the xml to be *pretty printed* and/or *validated*  then you can use the ```-x``` command line flag and it won't reformat the xml after processing when lxml is available.

**Comment by DavidHaslam** [comment]
@adyeths 

This issue was not about **pretty print**.

**Pretty print** can cause changes to significant whitespace in an XML file.

Even if one were to apply `xml:space="preserve"` during **pretty print**, though that would ensure that no significant whitespace is _deleted_, it doesn't prevent some significant whitespace being _added_. 

Having most of the XML content after the header to be more or less one continuous line with no breaks makes it very difficult for human being to inspect it within a suitable text editor.

It also makes it almost or completely impossible to search for patterns even when line wrap is enabled in the editor.

A line break after the end of each verse (& chapter) would improve the human readability of the XML, and (more important) inserting the new lines there should not involve adding significant whitespace, even in a Bible with sections and paragraphs.

**Comment by adyeths** [comment]
Use the ```-x``` command line flag. Your problem will be solved.

**Comment by DavidHaslam** [comment]
You said earlier (in effect) that "use the **-x** command line flag and it won't _reformat_ the xml".

I was assuming that it was because Cyrille had _not_ pretty printed his XML that he had used the **-x** command line option, and that was why most of the processed XML was linearized.

The issue is that for accuracy of preserving whitespace inthe converted Bible data, I do not wish to use pretty print, yet I do wish to be able to read the XML file more easily in a text editor.

One possible _ad hoc_ workaround might be as follows:

Replace all `> <` by `>\n<` where `\n` is the line feed character.

A space between XML elements is significant, yet a new line is the same as a space in terms of significant whitespace.

**Comment by adyeths** [comment]
Did you try what I said? If not, stop arguing and try it. If it doesn't work THEN get back to me.

**Comment by DavidHaslam** [comment]
Unlike my old Windows 7 PC, my newer Windows 11 PC is not yet setup to use Python, etc.
It may be a long time before I can get back up to speed, and there are lots of other things to sort out before that.

I'm not arguing!
I'm just trying to make sense of the **u2o** output that Cyrille has made on his Linux machine.
