### ISSUE TITLE
Validating the OSIS XML after the Bible Technologies website went AWOL ?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#121]
Some XML validation tools fail because the external XSD file specified in line 2 of the output is not found, due to the fact that the Bible Technologies website went AWOL several years back.

A useful solution would be to use the latest [OSIS schema](http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd) maintained by CrossWire.

See [https://wiki.crosswire.org/OSIS_211_CR](https://wiki.crosswire.org/OSIS_211_CR)

eg. As suggested in [https://gitlab.com/crosswire-bible-society/ukogienko/-/issues/1](https://gitlab.com/crosswire-bible-society/ukogienko/-/issues/1)

**Comment by adyeths** [comment]
u2o automatically validates it's output when the python lxml library is available unless told not to validate. I'm not going to switch to using crosswire's modified osis schema. This was previously discussed. I haven't changed my mind.
