### ISSUE TITLE
u2o doesn't manage the \ va tag

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#13]
Hi,
The script refuse the books with the \va \va* tag and stop to run.

**Comment by adyeths** [comment]
I need more information than this to resolve the problem.

**Comment by adyeths** [comment]
I downloaded the latest LinVB usfm source from your gitlab page and tested u2o on it to see how the va tags were handled. All va tags were handled as expected. There were other issues unrelated to va tags that appeared, though.

1. Deuteronomy has 2 tags that were not handled… \ip and \it.
2. 1 Maccabees didn't validate after conversion.

I will look into these issues.

**Comment by DavidHaslam** [comment]
Deuteronomy has a missing end tag `\it*` in the first introduction paragraph.

Already reported to the LinVB repo.

**Comment by adyeths** [comment]
There is a missing space after the \ip tag on line 11 in Deuteronomy. I still have to look at 1 Maccabees.

**Comment by adyeths** [comment]
Since the current issues are unrelated to va tags, I will close this and open a new one to address what is happening in 1 Maccabees. That one will take more time to figure out.

**Comment by LAfricain** [comment]
>Deuteronomy has 2 tags that were not handled… \ip and \it.
>1 Maccabees didn't validate after conversion.
Done

**Comment by LAfricain** [comment]
Yes it was my files the guilty!

**Comment by DavidHaslam** [comment]
`u2o.py` converts `\va_#\va*` and similar tags to **milestone** elements.

Such items do not display in SWORD front-ends.

Surely the purpose of an alternative verse number is that it should be visible to the user?

**Comment by adyeths** [comment]
Whether software actually shows the alternate verse number is not an issue with u2o. It's an issue with the software which renders the osis.
