### ISSUE TITLE
Tag Mismatch

### ISSUE THREAD

**Issue by adyeths** [adyeths/u2o#14]
xmllint reports a tag mismatch in 1 Maccabees when converting the [LinVB](https://gitlab.com/lafricain79/LinVB) to osis.

**Comment by DavidHaslam** [comment]
The OSIS XML file that I just made for **1 Maccabees** from LinVB validates against 
"http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd"

[TEST.osis.xml.zip](https://github.com/adyeths/u2o/files/1458693/TEST.osis.xml.zip)

That might be a clue. It must be an element that's now allowed by CrossWire but not in OSIS 2.1.1

**Comment by DavidHaslam** [comment]
Ignoring the space before `/>` the only substantial difference is here:
u2o.py
```
<div type="section">
<title>MAKABE 1</title>
</div>
<div type="section">
<chapter sID="1Macc.1" osisID="1Macc.1" n="1"/></div>
<title>Alesandro na bakonzi ba Greke</title>
```

my u2o2.py
```
<div type="section">
<title>MAKABE 1</title>
<chapter sID="1Macc.1" osisID="1Macc.1" n="1"/></div>
<div type="section">
<title>Alesandro na bakonzi ba Greke</title>
```

The issue seems to be the lack of a `</div>` for the end of the introduction section div.

**Comment by DavidHaslam** [comment]
I agree the line is spurious and unnecessary.
```
\s1 MAKABE 1 
```
lAfricain has been editing headers recently, so this may be one he easily missed.

Thanks for your help.

**Comment by adyeths** [comment]
The introduction section div is closed properly.

The main difference between the two files is that the chapter marker in your version is included in the div that is created for the \s1 marker I identified as being problematic for u2o. Whereas in the output from the current version of u2o, it is in the div for the following \s1 marker.

Now I need to think about how to handle this situation…

**Comment by DavidHaslam** [comment]
Isn't the real issue that a USFM file ought not to have a `\s1 ` tag before the `\c 1` ?

Any section title before the first chapter should be part of the introduction and must use the `\is# ` tag.

I don't really think the issue is with your script.

**Comment by DavidHaslam** [comment]
I've advised him to remove the line.

**Comment by LAfricain** [comment]
Done... Still my file the guilty :)

**Comment by adyeths** [comment]
This was caused by a bug in u2o's postprocessing routine. It is fixed now.
