### ISSUE TITLE
Warning required if two separate USFM files have the same \id ?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#15]
It shouldn't have happened, but our friend just ran `u2o.py` on a set of usfm files in which two files both have the same `\id INT`.

One of these files was supposed to have been removed!

The question is how should `u2o.py` respond when there are inadvertent duplicate `\id` like this?

Shouldn't there be some kind of warning?

**Comment by DavidHaslam** [comment]
See https://gitlab.com/lafricain79/LinVB/issues/38

**Comment by adyeths** [comment]
u2o is a conversion utility, not a validation utility. As such, it was never designed and is not intended to do anything at all to validate it's input. It's designed to do one specific job… take the usfm files that it is fed and convert them to osis. Checking to make sure multiple files do not have the same id would fall under the category of validation.

Validation is best done with a different tool that was designed to validate the usfm files before feeding them to u2o for conversion.
