### ISSUE TITLE
The script does not provide the attribute canonical="true" for a book division

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#16]
For book divisions (except peripherals, etc) the **div** element should include the **attribute** `canonical="true" `.

Refer to the detailed description & explanation in the OSIS 2.1.1 Reference.

**Comment by adyeths** [comment]
Which page in the osis manual says this attribute is required? I didn't see this when I looked at the manual.

**Comment by adyeths** [comment]
Btw, I'm not saying I'm not going to do this. I'm just curious where the manual says it was required. The original reason why it was not done was because I didn't see anything in the manual saying it was required. (It's an easy fix.)

**Comment by DavidHaslam** [comment]
There's a lot of discussion in the OSIS Reference about the use of the canonical attribute.

Use the search feature in Acrobat Reader or whatever program you use to display PDF.
(I currently use Sumatra PDF for Windows).

**Comment by DavidHaslam** [comment]
The canonical attribute is inherited.

This means that if it's applied at book division level, it would apply to all elements below.

This raises a special concern for titles. 
- Some translations include non-canonical titles for sections and/or chapters.
- For translations that have them as titles rather than verse text, 116 Psalms have a canonical title translated from the Hebrew.

Further observations.
- Canonical titles should not be hidden when headings are not displayed.
- The JSword front-end Bible Desktop implements this correctly.

**Comment by DavidHaslam** [comment]
The meaning of the word 'canonical' seems a bit ambiguous in the OSIS Reference.

This is probably because OSIS can be used for General Books (etc) as well as Bibles.

**Comment by DavidHaslam** [comment]
See also [OSIS Bibles](https://crosswire.org/wiki/OSIS_Bibles#Body) in the SWORD developers' wiki.

Note 3 states:

> Any **div** element defaults canonical to false. You need to set it to true on elements representing the structure of the original text.

**Comment by DavidHaslam** [comment]
From the OSIS Reference: (p. 18)

> When canonical="true", it means that the content of that element is a part of the text being encoded. For example, the "text" of the Bible includes the content of books, chapters, and verses but does not include notes, section-headings added by editors or translators, etc. Therefore, the default value for elements such as note is false, as the content of that element has been added by an editor or author to the text being encoded. _It should be explicitly noted that the value of the canonical attribute should not be used to reflect theological judgment about the content of a text, but merely to distinguish between what has been added to the text and what has not._

**Comment by DavidHaslam** [comment]
From the OSIS Reference: (p. 18)

> When canonical="true", it means that the content of that element is a part of the text being encoded. For example, the "text" of the Bible includes the content of books, chapters, and verses but does not include notes, section-headings added by editors or translators, etc. Therefore, the default value for elements such as note is false, as the content of that element has been added by an editor or author to the text being encoded. _It should be explicitly noted that the value of the canonical attribute should not be used to reflect theological judgment about the content of a text, but merely to distinguish between what has been added to the text and what has not._

**Comment by DavidHaslam** [comment]
**Cosmetic improvement:**

As OSIS book abbreviations vary in length, it would be better if the **canonical** attribute were to be placed between the **book** attribute and the **osisID** attribute, such that the amount of "raggedness" in XML folded view is minimised.

**Comment by adyeths** [comment]
xml doesn't care about the order of attributes in elements. Reordering the attributes is just busywork. This is not something I will focus on unless I am incredibly bored and have absolutely nothing else whatsoever to do but still feel the need to do something.

**Comment by DavidHaslam** [comment]
I had a bright thought yesterday after rereading part of the **OSIS User Manual**.

We could have done this _more economically_ by merely adding ` canonical="true"` to the end of the osisText element. e.g.
```
  <osisText osisRefWork="Bible" osisIDWork="Coverdale" xml:lang="en" canonical="true">
```
Because the canonical attribute is _inherited_, this would automatically apply to the **div** elements below for each book.

Currently, **u2o** doesn't do this.

btw. I ought to edit the CrossWire wiki page for [OSIS Bibles](https://crosswire.org/wiki/OSIS_Bibles#Body)  to document the inheritance of canonical values.
_I think note 3 in that section is misleading, don't you?_

**Aside:** Though it would also be inherited by the **header** element, in practice this matters not, as the header is not made part of a SWORD module built with **osis2mod**.

What think ye? @adyeths

**Comment by DavidHaslam** [comment]
See also https://crosswire.org/wiki/Talk:OSIS_Bibles#Misleading_advice_about_the_canonical_attribute.3F

**Comment by DavidHaslam** [comment]
See new issue #35
