### ISSUE TITLE
Top level div element types

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#18]
`u2o.py` does not make use of the `<div type="bookGroup">` element for grouping OT and NT books.

For USFM files that are not a Bible book, such as `\id INT`, surely `<div type="book">` is inappropriate?

cf. "book" has a particular meaning in the OSIS Referenece.

> The **div** element is used for many top-level components, and makes heavy use of the **type** attribute. The predefined types include the most common major divisions found in present-day Bibles and related works, for example:
>
> **• acknowledgement • appendix • article • back • body • book • bookGroup • chapter • colophon •
commentary • concordance • front • glossary • index • introduction • map • preface • section •
subSection**
>
> The main body of a Bible will typically consist of **div** elements of `<div type="bookGroup">` (such as each Testament, the Apocrypha, and perhaps smaller groups such as the Pentateuch, the Minor Prophets, etc), plus any front and back matter divisions (the selection of which varies greatly between editions).

NB. For brevity, I've omitted other attributes for the **div** element in this issue, but the **canonical** one is clearly relevant.  cf. Having `canonical="true"` at the **bookGroup** level would obviate the need to have it at **book** level.

**Comment by DavidHaslam** [comment]
Further thought.

For a set of USFM files that includes some DC books, the user would need to choose whether these are to be included in the OT bookGroup or whether they should be in their own DC bookGroup.

A command line switch may be advisable.

**Comment by DavidHaslam** [comment]
Aside: Using `osisID="INTRODUCTION"` seemed bizarre!

**Comment by adyeths** [comment]
Given the ability to have arbitrary book ordering in u2o... I don't think this is something that I will ever be able to implement in a manner which makes any kind of sense whatsoever to anyone, if it's even possible to do at all. If I only ever let people generate a single book order, this could be done. But that's not a limitation I want to impose.

**Comment by DavidHaslam** [comment]
Even so, the USFM files such as `\id INT` should **not** be `<div type="book">`.

This aspect of the issue you have ignored - please reconsider!

**Comment by adyeths** [comment]
The div type used for front and back matter can be changed. That's a separate issue unrelated to bookgroups though. Feel free to implement bookgroups yourself if you think it can be done in a manner which allows for arbitrary book ordering. I'm not convinced its possible.

**Comment by DavidHaslam** [comment]
cf. The issue title is "**Top level div element types**" - it's not merely "**bookGroup**" divs.

Of course, **bookGroup** divs can be implemented by _postprocessing_ the XML file.

In the absence of any provision in `u2o.py`  this is what we'll have to resort to for the time being.
