### ISSUE TITLE
Please could we have a better way to handle the \cl marker ?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#20]
You recorded:
```
    # The OSIS user manual says to convert these to titles and use chapterLabel
    # for type in the title tag. That type is not allowed according to the OSIS
    # 2.1.1 schema though. So I use x-chapterLabel for the type instead.
    # NOTE: titles created in this manner don't work with The SWORD Project
    #       software and create problems with displaying other titles as well.
    #       So the conversion to titles is disabled for now and milestone
    #       markers are inserted instead.
    # r'\cl': ('<title type="x-chapterLabel" short="', '"/>'),
    # r'\cl': ('<milestone type="x-chapterLabel" n="', '"/>'),
```
My preferred way of handling `\cl_text` is:
```
    # DFH:  I recommend the following in place of what Adyeths decided above.
    #       This works with OSIS and with SWORD.
    r'\cl': ('<title type="chapter" canonical="false" subType="x-chapterLabel">', '</title>'),
```

btw. Is there a problem specific to _The SWORD Project for Windows_ that we don't know of?
Or did you merely mean the SWORD API ?

Title elements are independent of each other, so how could using one here cause a problem for other titles?

**Comment by DavidHaslam** [comment]
btw. The **LinVB** project makes use of `\cl ` for longer text than most other projects we've come across.

[LinVB search results for chapter label.txt](https://github.com/adyeths/u2o/files/1470819/LinVB.search.results.for.chapter.label.txt)

Clearly, it's important that these text items should be displayed by SWORD.

**Comment by DavidHaslam** [comment]
The other factor relating to `\cl ` is its position dependence as described in the **USFM User Reference**.

> **Usage note:**
>
> If \cl is entered once before chapter 1 (\c 1) it represents the text for "chapter" to be used throughout the current book. If \cl is used after each individual chapter marker, it represents the particular text to be used for the display of the current chapter heading (usually done if numbers are being presented as words, not numerals).

_Aside: I've yet to see this implemented properly in any of the USFM conversion scripts._

**Comment by DavidHaslam** [comment]
**Further thought:**

Chapter "numbers presented as words" might include the use of Roman numerals.

i.e. Because Bible software would be unlikely to use those otherwise.

**Comment by adyeths** [comment]
with regards to this...

`
    # NOTE: titles created in this manner don't work with The SWORD Project
    #       software and create problems with displaying other titles as well.
    #       So the conversion to titles is disabled for now and milestone
    #       markers are inserted instead.
`

... there is no mention of the sword project for windows because the problem is not with software running on a specific operating system. I have personally experienced this problem when using other frontends. That's why I had to change how this tag was processed in u2o.

With regards to the cl tag's position dependence issue... *u2o handles that in an appropriate manner*. That is, if cl is used once before chapter 1, then there are appropriate chapter headings added to all chapters in the osis that is generated.

With regards to the cl tag's contents actually being used appropriately by software that renders osis, that's a matter for the whatever library and frontends make use of the osis files.

**Comment by DavidHaslam** [comment]
You still haven't described the nature of the problem?

btw. I only asked about SPW because you used the exact phrase "The SWORD Project".
"The SWORD Project for Windows" is the name of the front-end that was at one time the flagship program of CrossWire. Had you merely mentioned 'SWORD' - I wouldn't have queried it.

**Comment by DavidHaslam** [comment]
Just because some Bibles may have other titles at the start of a chapter such that the additional use of a chapter label title might begin to make the display overbearingly cluttered - that's no reason to hide the chapter label marker for a project where it might (for one book at least) be the only title for each chapter.

This is the case with the Psalms in the LinVB project of lAfricain.
It's not the only such project where a title element is the right thing to use.

**Comment by adyeths** [comment]
The chapter label is available to be used by any software which renders osis. It's up to the software which renders osis to actually make use of it, though. I have no control over that.

The only reason it's not specifically specified as a title tag right now is because the title tag that I used caused other titles not to display.

**Comment by DavidHaslam** [comment]
> The only reason it's not specifically specified as a title tag right now is because the title tag that I used caused other titles not to display.

A software bug in a front-end is not part of your brief !

i.e. Not to use as a justification for refusing to retain a title element to implement chapter labels.

- Did you report the bugs to the relevant front-end developers?
- Can the problem be reproduced and repeated?

**Comment by adyeths** [comment]
I'm not going to argue this ad nauseum. The title tag I used (which was how the osis manual said to encode chapter titles) caused problems so it was replaced with a milestone tag to preserve the information. The title tag I used didn't even cause a title to be displayed even where it wasn't causing problems. Nothing was lost by changing it to a milestone. It's still marked as a chapter title. It can still be used by software which renders osis. It's up to the software to make use of the information. Whether they use this information or not is not my concern.

As for reporting bugs, no I didn't report it. I've tried reporting bugs to them in the past. They were ignored. I learned my lesson and moved on.

And that's all I will say regarding this matter.

**Comment by DavidHaslam** [comment]
I must give you _full marks_ for responsiveness (certainly compared to what others are like).

But for the record, our flagship KJV module makes ample use of the **title** element for chapter labels.

```
<chapter osisID="Ps.3">
<title type="chapter"><abbr expansion="Psalm"><hi type="spaced-letters">PSAL</hi>.</abbr> III.</title>
```

_Admittedly SWORD does not yet support the above new hi type, but that's a side matter._

We did not include `subType="x-chapterlabel"`, even though that's what it really is.
Nor is it the case that our OSIS source text was converted from USFM.

But you must be able to see my point that this really works (inasmuch as it can for minor aspects).

Moreover, it does not interfere with the next element which is:
```
<title canonical="true" type="psalm" osisID="Ps.3.1!title"><w lemma="strong:H04210">A Psalm</w> <w lemma="strong:H01732">of David</w>, <w lemma="strong:H01272" morph="strongMorph:TH8800">when he fled</w> <w lemma="strong:H06440">from</w> <w lemma="strong:H053">Absalom</w> <w lemma="strong:H01121">his son</w>.</title>
```

I'm still at a loss to understand how one sort of title simply did not display when you originally tried.

**Comment by DavidHaslam** [comment]
We should also remember that the documentation in the **OSIS 2.1.1 Reference** did contain a few errors.
