### ISSUE TITLE
Peripheral USFM files should not become div type="book"

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#23]
The **type** attribute value for the **div** element made from (e.g.) `\id INT` should be `"introduction"` rather than `"book"`.

cf. "book" has a particular meaning in the OSIS Referenece.

> The **div** element is used for many top-level components, and makes heavy use of the **type** attribute. The predefined types include the most common major divisions found in present-day Bibles and related works, for example:
>
> **• acknowledgement • appendix • article • back • body • book • bookGroup • chapter • colophon •
commentary • concordance • front • glossary • index • introduction • map • preface • section •
subSection**

Some of the other peripheral USFM `\id ` tags will have a corresponding type value _predefined_ in the OSIS schema, though some will not. For the latter, it would be sensible to use a value with the `x-` prefix.

**Comment by adyeths** [comment]
The type attribute for a div element made from `\id INT` is already `"introduction"` rather than `"book"`. This was already fixed.

**Comment by DavidHaslam** [comment]
Thanks for that.

Been multitasking today, and made the wrong assumption that lAfricain was tracking your changes and and always using your latest version. Too much on my mind at present, so it's not surprising that I hadn't realised you'd already fixed this.
