### ISSUE TITLE
Suggestion: include revisionDesc element in header

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#25]
Just a thought.

It could be useful for `u2o.py` to generate a suitable **revisionDesc** element in the OSIS header.

This could include:
- a **date** element with a timestamp from the OS
- a **p** element with the text `Converted from USFM files using u2o.py version #, last updated yyyy-mm-dd.`
- a **p** element promoting the GitHub repo for u2o (if you'd like to advertise)
- a further **p** element containing any text specified in the command line with a new option

The last suggestion is not essential, but may help traceability.

**Comment by adyeths** [comment]
An initial revisionDesc in the osis header makes sense. It's been added.

**Comment by DavidHaslam** [comment]
Might it be feasible to include the attribute `resp="username"` by picking up an environment variable?

**Comment by adyeths** [comment]
I have added `resp="username"` to the revisionDesc and also made orefs include it's own revisionDesc.

**Comment by DavidHaslam** [comment]
I will test it to see if that will work in CygWin on my Windows 7 PC.

Slight worries about whether the environment variable name might not be recognised.

Not tried using one in CygWin before.
