### ISSUE TITLE
Improving the error message for Unknown encoding?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#28]
All the USFM files I just received for a project contain this line:
```
\ide Unicode (UTF8)
```
The **USFM User Reference** states:
### \ide_&lt;ENCODING>
- An optional character encoding specification. 
- This marker should be used to specify the character encoding of the text within the file. For example: CP-1252, CP-1251, UTF-8, UTF-16, OR Custom <specify font name>. If the character encoding does not conform to a known standard, but is rather a customized solution for the project, a minimum of the name of the font used for the project should be included. For archive purposes, texts which rely upon a custom encoding solution should be converted to Unicode, if at all possible. 
### Examples 
Text - Matthew (GNT)
```
\ide UTF-8
\ide CP-1252 
\ide Custom (TGUARANI.TTF)
```

`u2o.py` gave this message:
```
ERROR: Unknown encoding... aborting conversion.
```

Maybe the message should cite the text found in the `\ide ` tag, in order to help less familiar users to know where the problem lies?

**Aside:** Using the script with `-e UTF-8 ` as part of the command line allowed it to process OK.

btw. I've not yet encountered one that has the allowed 
```
\ide Custom (FONTNAME.TTF)
```

**Comment by adyeths** [comment]
done.
