### ISSUE TITLE
Converting untagged references in ordinary footnotes

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#31]
### Some ordinary footnotes contain a scripture reference

The data within the attached file was extracted from a project I'm currently working on.
[merged.notes.usfm.zip](https://github.com/adyeths/u2o/files/1522098/merged.notes.usfm.zip).

NB. There are no _cross-reference_ markers (`\x ... \x*`) anywhere in this **Urdu** translation.

Five wordy footnotes contain an _untagged_ scripture reference. e.g.
```
\f + عام طور پر عبرانی میں افود کا مطلب امامِ اعظم کا بالاپوش تھا (دیکھئے خروج 28:4)، لیکن یہاں اِس سے مراد بُت پرستی کی کوئی چیز ہے۔ \f*
\f + عام طور پر عبرانی میں افود کا مطلب امامِ اعظم کا بالاپوش تھا (دیکھئے خروج 28:4)، لیکن یہاں اِس سے مراد بُت پرستی کی کوئی چیز ہے۔ \f*
\f + دیکھئے خروج 30:11-16 \f*
\f + ایک اَور ممکنہ ترجمہ: تُو نے اُسے تھوڑی دیر کے لئے فرشتوں سے کم کر دیا (دیکھئے عبرانیوں 2:7،9)۔ \f*
\f + عبرانی میں ’عمانوایل‘ لکھا ہے، دیکھئے 7:14 کا فٹ نوٹ۔ \f*
```
_That two of the footnotes are identical is immaterial. They are in different but nearby verses._

NB. The reference in the third note is actually at the **end** of the footnote text.
- i.e. GitHub has some issues rendering mixed LtR and RtL text.

Might it be feasible enhance **u2o** to convert these **untagged references** to proper OSIS reference elements?

**Comment by DavidHaslam** [comment]
You thought it would be a fun project.  :)

**Comment by adyeths** [comment]
Maybe… but this seems more like something that should be fixed in the usfm source.

Yes indeed, I did think it would be a fun project. I was right too. It was, and still is, a fun project. :)

**Comment by DavidHaslam** [comment]
Except that in the **USFM User Reference**, it very much seems that it's a case of _either/or_.
- Ordinary footnotes that are all (or mostly) text &ndash; that use the `\f ...\f*` marker set
- Cross-reference notes that are only (or mostly) scripture references (with punctuation and occasionally a few short words) &ndash; that use the `\x ...\x*` marker set

Certainly, I've never seen a case of `\x ...\x*` markers being used within `\f ...\f*`.

I suspect that it's not valid to do that, and that **ParaTExt** would complain.

Thus the possibility to fix it in USFM source text seems very unlikely.

**Comment by DavidHaslam** [comment]
btw. In the Urdu footnotes I provided as an example, there are certainly improvements that can be scripted, but this is not one of them.

**Comment by DavidHaslam** [comment]
Standalone verse numbers found within footnote text may be suitably marked using the _nested character markup_ version of the **footnote verse** marker `\+fv ##\+fv*`

**Comment by DavidHaslam** [comment]
In the end, we improved the markup in the SFM files to use `\+xt ...\+xt*` which has very wide application.
See [USFM issue 34](https://github.com/ubsicap/usfm/issues/34)

_Only 5 of the 354 notes in **UrduGeo** source text required this markup._

**Comment by adyeths** [comment]
Sounds like this has been fixed in the usfm source. So I will close this issue now.
