### ISSUE TITLE
Please provide support for nested character syntax in footnote verse tags

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#34]
### Footnote verse number
**\fv_##\fv***
· Footnote verse number. 
· To mark a verse number in the the text quotation or alternative translation. 
> This marker will typically be nested within another footnote content element, like \ft, \fq or \fqa.
_See  Nesting Character Markup for  details._

i.e. Implement the conversion of :
**\\+fv_##\\+fv***

NB. I myself only just discovered this aspect, and it is now being used in a project that I'm assisting with.

**Comment by adyeths** [comment]
Should be implemented now.

**Comment by DavidHaslam** [comment]
Thank you.

**Comment by DavidHaslam** [comment]
Please re-open #34 &ndash; I think there's a software bug.  

- The `</hi>` appears **too late**!

It should be just after the **verse number**, where the `\+fv*` is in the respective SFM file.

There are 8 notes in this **Urdu** translation that make use of `\+fv ##\+fv*`
The attached analysis was extracted from the XML note elements.
[Bible.UGV.notes.super.txt](https://github.com/adyeths/u2o/files/1539464/Bible.UGV.notes.super.txt)

btw. The **seg** elements with `type="x-nested"` were properly applied.

**Comment by adyeths** [comment]
check the usfm source to make sure there is a closing tag and that it immediately follows the number and doesn't include the extra text.

**Comment by DavidHaslam** [comment]
The USFM was correct. This example is from **1KI**. The script is Urdu.
```
\f + \fr 18:26 \fq ناچتے رہے: \ft لفظی ترجمہ: \fqa لنگڑاتے ہوئے ناچتے رہے۔ \ft غالباً بعل کی تعظیم میں ایک خاص قسم کا رقص۔ لہٰذا آیت \+fv 21\+fv* میں الیاس کا سوال، ”آپ کب تک . . . لنگڑاتے رہیں گے؟“ \f*
```
The OSIS for this part of verse 26 was:
```
<note placement="foot"><reference type="annotateRef">18:26 </reference><catchWord>ناچتے رہے: </catchWord>لفظی ترجمہ: <rdg type="alternate">لنگڑاتے ہوئے ناچتے رہے۔ </rdg>غالباً بعل کی تعظیم میں ایک خاص قسم کا رقص۔ لہٰذا آیت <seg type="x-nested"><hi type="super">21 میں الیاس کا سوال، ”آپ کب تک . . . لنگڑاتے رہیں گے؟“ </hi></seg></note>
```
_NB. To reduce clutter, I have omitted the verse text outside the note._

**Comment by DavidHaslam** [comment]
#### Aside: 
There's ongoing discussion about whether some of these notes should actually use **\fv** or not.
But that's quite a separate matter than what appears to be a bug in **u2o**.

**Comment by adyeths** [comment]
This is going to take me a while to fix. There seems to be a problem with the notefix regular expression but I'm having trouble figuring out what it is. (regular expressions give me problems. That's why I try to avoid them. It's far too easy to mess something up inadvertently and then have things go horribly wrong with them.)

**Comment by adyeths** [comment]
Ok I guess I was being a bit overly pessimistic with regards to the amount of time it would take for me to figure this out. lol. It should be fixed now.

**Comment by DavidHaslam** [comment]
_Thanks. I will download and test it shortly._

Meanwhile, FYI. We've received expert advice regarding usage. I thought it worthwhile sharing.

> If what you are seeking to do is to mark a reference that you are directing the reader to, you can use **\xt ..\xt***. When that is nested within another character style, it should use nested syntax - so **\+xt ...\+xt***
> 
> **\xt** is permitted widely. It can be used nearly anywhere you are wishing to mark a "target reference". In **Paratext 8** it will also cause the reference checker to engage and display whether the syntax is correct and the target reference exists.

**Comment by DavidHaslam** [comment]
Here's the evidence which confirms that the fix was successful. @adyeths 

[Bible.UGV.notes.super.txt](https://github.com/adyeths/u2o/files/1540278/Bible.UGV.notes.super.txt)

_Many thanks._
