### ISSUE TITLE
Add canonical="true" to the osisText element

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#35]
See my latest comment in #16 

If this is done, because the **canonical** attribute value is _inherited_, do we still need it in **div** elements with `type="book"` ?

**Comment by adyeths** [comment]
If I did this, I wouldn't need to have the canonical="true" in the book div's. I would have to add a canonical="false" to the divs for other content, such as front and back matter then. Since I already added the canonical="true" attribute to the bible books, making this change is unnecessary.
