### ISSUE TITLE
Parsing bookless references without any defined book names or abbreviations?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#37]
### Parsing references with orefs.py

For a translation that contains _no_ explicit **cross reference** markers using `\x + ...\x*` but does have copious **footnotes** using `\f + ...\f*` and for which a few contain a **reference** tagged as `\+xt ...\+xt*` &ndash; then in theory it should be feasible to convert these to provide the correct **osisRef** values even though _no_ book names or abbreviations are defined either by `toc# ` markers or in the configuration file.

i.e. When these references are to somewhere in the current book or even to the current chapter, and thus they _omit_ the book name because that's implied by the context.

Here's an example: (**UrduGeo**)
```
<verse sID="Judg.8.27" osisID="Judg.8.27" n="27" />اِس سونے سے جدعون نے ایک افود<note placement="foot"><reference type="annotateRef">8:27 </reference><catchWord>افود: </catchWord>عام طور پر عبرانی میں افود کا مطلب امامِ اعظم کا بالاپوش تھا (دیکھئے خروج <seg type="x-nested"><reference>28:4</reference></seg>)، لیکن یہاں اِس سے مراد بُت پرستی کی کوئی چیز ہے۔ </note> بنا کر اُسے اپنے آبائی شہر عُفرہ میں کھڑا کیا جہاں وہ اُس کے اور تمام خاندان کے لئے پھندا بن گیا۔ نہ صرف یہ بلکہ پورا اسرائیل زنا کر کے بُت کی پوجا کرنے لگا۔
<verse eID="Judg.8.27" />
```

In principle, it ought to be straighforward to change 
`<reference>28:4</reference>`
(currently generated by `u2o.py`) to 
`<reference osisRef="Judg.28.4">28:4</reference>`

Q. Is this already implemented?

**Comment by adyeths** [comment]
The reference tag should be created by u2o if there is `\+xt …\+xt*` present in the footnote. If it doesn't, then I would consider that a bug.

The orefs utility can't create a proper osisRef attribute unless a book name (and a chapter) is specified in the reference. It doesn't make assumptions about which book (or chapter) is supposed to be used.

If I change orefs to require the use of lxml, then I could make it use the current book for references that omit the book. I'm not optimistic about being able to make it handle references that omit the chapter.

**Comment by DavidHaslam** [comment]
It should make the same assumptions as does ParaTExt.

A bookless reference (e.g. **18:26** ) should be to the current book. 
See #36 &ndash; the details supplied by Jeff Klassen.

Surely you can capture the bookname up as a variable from the **osisID** in the book **div** ?
_That's how I'd do it._

In anycase, you need it for inserting into all the **reference** elements with `type="annotateRef"`.

**Comment by adyeths** [comment]
What ParaTExt does is not necessarily what I'm going to be able to do. It's far more complex and has far more people contributing to it's development than I have with this project. There might be some things I can do. But I'm never going to be able to do everything that it can do.

Right now orefs doesn't do anything with references that have a type of "annotateRef" unless there is a book name present in the reference (which is unlikely).

It's not impossible to do without lxml. It would just be significantly easier to do using lxml. (Though, I have been thinking about this issue and have some ideas on how to process bookless references without lxml.) Requiring lxml wouldn't be a major issue. Most people who process xml with python would likely already have it installed.

**Comment by DavidHaslam** [comment]
**ParaTExt** is the _de facto_ test bed implementation for USFM, and will be the effectual way in whcih USFM gets used and validated. That will be the case even while official USFM documentation is lagging due to workload pressures on those involved.

According to Jeff K, the documentation updates should be done in January 2018.

**Aside:** I'm a **Windows 7** user. I use **Python 2.7** in **CygWin** to run Python scripts such as yours.
I've not got round to figuring out how to install **lxml**, so I've not yet given it a whirl.
So when it comes to validating the OSIS, I just use the **XML Tools** plugin of **Notepad++**.

After downloading your repo and extracting the files, I now make a couple of minor edits in `u2o.py`
1. Python **2.7** in  line 1
2. Use **z:/** as the location path for the `osisCore.2.1.1.xsd`  file in line 123.

cf. I have **subst z:** to the path where I stored the schema.

**Comment by DavidHaslam** [comment]
I wonder whether anyone would ever be inclined to develop an **XSLT** to convert **USX** to **OSIS** directly?

They'd still face many of the challenges that a Python programmer has faced, but at least the input files would already be a type of XML.

One disadantage for that route is that it would be of no help for those translations being edited or converted by workers that are _not_ registered to use **ParaTExt**. 

e.g. For anyone using **Bibledit**, or those like myself and others, that do things like making SWORD modules.

**Comment by adyeths** [comment]
It would be a good idea to move to python3. Python2 will not be officially maintained beyond 2020. (This was one of the motivations for creating u2o.)

I don't know what usx looks like. But, being an xml format wouldn't automatically make it any easier to convert to another xml format. It may require just as much work converting to osis as usfm. I have contemplated the idea of creating a usx to osis converter at various times. But there doesn't seem to be much interest in such a thing. There doesn't seem to be an actual need either. It is for these reasons that I haven't pursued it.

**Comment by adyeths** [comment]
Processing bookless references is now implemented.

**Comment by DavidHaslam** [comment]
Not yet looked how you did it.

I was doing something similar this morning with TextPipe.
Might be useful to compare notes.

Did you address the cases of a reference with a verse range and/or a verse sequence?

@adyeths

**Comment by DavidHaslam** [comment]
> I don't know what USX looks like. But, being an XML format wouldn't automatically make it any easier to convert to another XML format. It may require just as much work converting to OSIS as USFM. I have contemplated the idea of creating a USX to OSIS converter at various times. But there doesn't seem to be much interest in such a thing. There doesn't seem to be an actual need either. It is for these reasons that I haven't pursued it.

I think you're right on this. I was merely thinking aloud (as it were).
Robert H has asked one of his contacts in SIL if this was ever done.
