### ISSUE TITLE
Validate OSIS again after running orefs.py

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#39]
Just in case there are some unexpected contents within references
(e.g. an Arabic comma that escaped our attention)
it makes good sense to check that the OSIS is still valid.

This is also one good reason to also keep the two scripts _separate_.
Easier to find root cause of invalid OSIS before fixing xrefs and potentially "making things worse".

**Comment by adyeths** [comment]
An additional validation step isn't necessary. The only thing that changes in the osis is the addition of an osisRef attribute to the reference tags. And the way orefs is written there's only one particular case that I can think of where there could potentially be an issue. And that's the case where there is a single space after the reference and a single word following, such as this reference: `Deuteronomy 32:43 LXX`. The LXX part (or whatever would be in it's place) is simply appended to the front of the osisRef as "LXX:"... which will be problematic at some point. I'm still thinking about how to handle this better.

As for keeping orefs separate, I've been thinking that might be a good idea as well. I just haven't gotten around to changing the orefs readme to reflect this decision yet.

**Comment by DavidHaslam** [comment]
I didn't detect an Arabic comma until I attempted to validate after running my bespoke TextPipe filter. 

Just sharing a potentially useful observation.
