### ISSUE TITLE
When translators make parsing references difficult

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#43]
A potential pitfall is parsing a list of references in a translation has made such things difficult.

One example is when they have punctuated the number 1, 2 or 3 at the start of a bookname with a full-stop.

E.g. `1. Corinthians` rather than `1 Corinthians` (or with the abbreviation, likewise).

You can easily fall into the trap that the number is mistaken for a verse or a chapter in the previous book in the list of references, such as when (as in certain languages) verses in a list are separated by a full-stop rather than a comma.

There's no accounting for such idiosyncrasies in Bible translators and in customs for different languages.

I add this issue only because it's one I've faced in the past.  Hey ho!

Ambiguities like this may be more readily resolved by the human brain than by a machine.

**Comment by adyeths** [comment]
I already considered this possibility. As long as the period is included in the book names and abbreviations specified in the toc2 and toc3 tags or in the conf file, they will be handled correctly.
