### ISSUE TITLE
Reference errors - are these marked in situ (in addition to printing an error message) ?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#44]
What happens _in situ_ for those references that are not capable of being correctly assigned an **osisRef** ?

i.e. What should the user search for?

If there are many such erroroneous references, it would be simpler for the user to search for a string that could be used to mark all of them.

For example, they could be assigned a dummy **osisRef** value that will make the OSIS invalid.

e.g. `osisRef="###"` or, better still `osisRef="###.ch.vs"`, etc. 
where `.ch.vs` is for the correct chapter and verse numbers in the reference, if only the book abbreviation was not matched.

Having a **single search pattern** in the resulting invalid osis would make it easier for the user to locate in the _input_ osis file each reference that requires further attention.

_Please review.  Thanks._

**Comment by adyeths** [comment]
references that are not able to be correctly assigned an osisRef are left intact in the text of the reference tag. They are simply not added to the osisRef attribute. Adding an invalid osisRef is not something I wanted orefs to do. I didn't want it to render the osis invalid. I wanted it to add osisRef attribute where possible and notify the user of errors where it wasn't.

**Comment by DavidHaslam** [comment]
Is there then any _foolproof pattern_ the user could search for to find all the references that did not have the **osisRef** added?

In theory, a search for `<reference>` should work - except for those that may already have other attributes, but are there ever any like this?

Then one would need to search for the reference elements that do not contain `osisRef=`.

**Comment by adyeths** [comment]
Right now, the only way to find the reference is to use the the error message displayed when they ran orefs.

I will look into modifying orefs to add an xml comment to the reference text itself that could make it easier to locate. It may take some time. But that's as far as I'm willing to go. orefs should never cause valid osis to become invalid.

Keep in mind that when multiple references are included in a particular reference tag, some of them may have been processed. Simply searching for a reference tag without an osisRef attribute won't necessarily be enough.

**Comment by DavidHaslam** [comment]
I guess you're thinking of something like the miniature XML remarks already output by `u2o.py` such as 
`<!-- mt1 -->`  and `<!-- nb -->`

A unique pattern like that would be very useful.

**Comment by adyeths** [comment]
These are now marked with the following xml comment  `<!-- orefs - unprocessed reference -->`
