### ISSUE TITLE
orefs.py - what when there are two different abbeviations for the same book ?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#46]
When you're not the owner of a set of USFM files, you usually have no liberty to change them, unless you're in good contact with the owner, etc.

For a translation made by a team in which the work was split in (e.g.) a NT and OT committee, it can easily happen that without strict guidelines, part of the Bible uses one set of abbreviations in references and another part of the Bible uses a different set. This means you can end up with at least one book that has two different abbreviations.

The **config file** should be capable of accommodating such a scenario.

**Comment by adyeths** [comment]
The config file was added for exactly this reason, sometimes more than one abbreviation is needed. The script will loop through all the abbreviations provided in a config file when processing the osisRef attributes.

**Comment by DavidHaslam** [comment]
Please clarify this possibility in the README for orefs.py - thanks.

That would help users write the config file if they do face such a scenario.

If the notion isn't documented, they may simply assume it cannot be done.

**Comment by adyeths** [comment]
The example config file already includes an entry with more than one abbreviation for one of the books (Wisdom of Solomon). Aside from that, I would hope the users are smart enough to add the abbreviations they actually used in the text (or may use in the future) to the config file regardless of what the example config file showed.

I would rather spend time actually fixing problems in orefs (and improving u2o) than adding explanations that should be obvious (such as *add all the abbreviations that you actually used or may use in the future*) to the readme file.
