### ISSUE TITLE
More alternatives

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#48]
You may wish to include the following in the **README**

- [OSIS converters](https://github.com/JohnAustinDev/osis-converters) &ndash; by the **xulsword** developer

- [ParaTExt](http://paratext.org/) &ndash; Since version 6, has a menu option¹ to export to OSIS.

#### Note:
1. But read the reported experience in the Sword developers' wiki [page](https://crosswire.org/wiki/Converting_SFM_Bibles_to_OSIS#ParaTExt_.28export_to_OSIS.29)

**Comment by DavidHaslam** [comment]
Aside: `orefs.py` now has a mention at CrossWire.
See https://crosswire.org/wiki/Converting_SFM_Bibles_to_OSIS#orefs.py

**Comment by adyeths** [comment]
Those were left out intentionally.

1. OSIS converters uses usfm2osis.py for it's initial conversion to osis. It no longer uses it's own usfm to osis converter. It's more of an osis postprocessing tool now. If it still used its own usfm to osis converter then I would have linked to it.
2. ParaTExt is an excellent piece of software. But, it's limited with regards to who is actually able to use it. (For instance, I'm not able to use it.) Plus, according to the crosswire wiki, the results were rather poor with regards to it's osis export and it's osis export feature is no longer being improved. Linking to it just doesn't make sense to me.

**Comment by RobH123** [comment]
I don't think this is quite correct. I can't find anything about
      OSIS either in the Paratext 8 menus nor the help files.
    I think maybe the OSIS export comes from the SIL
        Pathway software plug-in (although I can't even see OSIS
      mentioned there).
    Robert.
    
    
    On 13/12/17 05:02, David Frank Haslam
      wrote:
    
    
      You may wish to include the following in the README
      
        
          OSIS converters – by the xulsword
            developer
        
        
          ParaTExt – Since version 6, has
            a menu option¹ to export to OSIS.
        
      
      Note:
      
        But read the reported experience in the Sword developers'
          wiki page
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adyeths/u2o","title":"adyeths/u2o","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adyeths/u2o"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"More alternatives (#48)"}],"action":{"name":"View Issue","url":"https://github.com/adyeths/u2o/issues/48"}}}
