### ISSUE TITLE
The URL for the OSIS schema needs to be corrected

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#5]
Your script uses
http://www.bibletechnologies.net/OSIS/osisCore.2.1.1.xsd
That gives a **404 error**!

The correct URL should be:
http://www.bibletechnologies.net/osisCore.2.1.1.xsd

Please update your script accordingly.

**Comment by adyeths** [comment]
Thank you. This is now fixed.

**Comment by DavidHaslam** [comment]
The Bible Technologies website went AWOL several weeks ago. 

One of my contacts is chasing to find out what's happened. 

Meanwhile, it would be simpler to host a copy of the 2.1.1 schema in your repo. 

Alternatively, to point to the copy of the released version 2.1.1 hosted on the CrossWire server. 

Not the latest CR version that we have available too.

**Comment by adyeths** [comment]
The osis 2.1.1 schema is already embedded in u2o. Another copy is unnecessary.
