### ISSUE TITLE
u2o.py doesn't manage well \x tags 

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#50]
The conversion of the diverses \x tags, are not good, example:
`\x + \xo Mal 3,1\x*` gives: `\x + <seg type="x-usfm-xo">Mal 3,1</seg>\x*`, `(tala \x + \xot Lev 11,44-45 ye 19,2 ye Iza 6,3\x*)` gives: `(tala \x + <seg editions="ot">Lev 11,44-45 ye 19,2 ye Iza 6,3</seg>\x*)`...
Maybe it is me that write not well the crossreferences tags?
The conversion with orefs.py seems also to be bugged.

**Comment by adyeths** [comment]
Regarding the conversion of \x tags... I'm not sure why it would leave parts of the usfm tags in the converted osis. That's not something I've encountered in other bibles that have had cross references. I will have to investigate this more.

Regarding orefs processing... it doesn't do any processing of seg tags in osis, it just processes reference tags. So not processing these seg tags is expected. I may have to try to add support for these particular seg tags. I will have to investigate this more.

Here's documentation on writing cross references if that's helpful: [http://ubsicap.github.io/usfm/notes_basic/xrefs.html](url)

**Comment by LAfricain** [comment]
Ok thank you, I'll wait :)

**Comment by adyeths** [comment]
I was not able to reproduce this error. u2o did the conversion correctly and didn't leave any parts of the \x tags behind afterwards.

**Comment by adyeths** [comment]
handling of the usfm xo tag in u2o is corrected so it produces a proper osis reference tag now.

**Comment by LAfricain** [comment]
For me the last commit doesn't yet solved the issue. Sorry :(

**Comment by adyeths** [comment]
The only thing the last commit fixed was conversion of \xo tags. They are now converted to <reference tags which should allow them to be processed by orefs.

In order to fix the problem with the main \x tag being left behind after processing I would have to be able to reproduce the error. I haven't been able to do that. When I run u2o on what you've provided above, it converts them fine without leaving behind parts of the tags.

**Comment by LAfricain** [comment]
I understand the problem, I used \x tag for footnotes! Now I understand well how to use the \fr and \ft together, it solved the problem.

**Comment by LAfricain** [comment]
Hello, 
It's still me... :) Now with a new bible (Vulgate) I have this warning for crossreferences in footnotes:
```
WARNING: Reference not processed… RevEstRev Rev11Rev,Rev2Rev-Rev12Rev,Rev6Rev
WARNING: Reference not processed… RevEstRev Rev13Rev,Rev1Rev-Rev7Rev
WARNING: Reference not processed… RevEstRev Rev13Rev,Rev8Rev-Rev14Rev,Rev19Rev
WARNING: Reference not processed… Rev15Rev,Rev4Rev-Rev19Rev 
WARNING: Reference not processed… RevEstRev Rev16Rev,Rev1Rev-Rev24Rev
WARNING: Reference not processed… RevEstRev Rev1Rev,Rev1Rev
Writing output to osis/vulg_ref.osis.xml 
```
 is orefs able to convert the \fr tag to crossreference?

The usfm text is: `\f + \fr Est 13,1-7\f*` It gives `<note placement="foot"><reference type="annotateRef">Est 13,1-7</reference></note>` with u2o, and `<note placement="foot"><reference type="annotateRef" osisRef="">Est 13,1-7<!-- orefs - unprocessed reference --></reference></note>` with orefs.

**Comment by adyeths** [comment]
orefs is saying it didn't know how to process these references and marking them so that manual fixes can be made. (Not entirely unexpected considering the difficulty in parsing cross references without a single standard way to write them.)

Did you use a config file when processing this text with orefs? If not then that's likely one of the problems here. I would recommend always using a config file that is specifically for the text you're processing.

**Comment by LAfricain** [comment]
> Did you use a config file when processing this text with orefs?

Yes I did. Should orefs  recognize the tag \fr? In the warning, what is strange it is that it doesn't recognize the numbers too!

**Comment by adyeths** [comment]
orefs doesn't do anything with usfm tags. u2o handles the usfm tags. orefs is only for adding osisRef attributes to the references tags in the osis files that u2o creates.

The \fr tags are being converted to reference tags by u2o, so there isn't a problem in that regard. My next suggestion is to make sure all of the abbreviations for the books are specified in the config file.

My testing of the above reference shows that it is processed correctly by orefs when the appropriate separators and abbreviations are specified in the config file.

**Comment by LAfricain** [comment]
> My next suggestion is to make sure all of the abbreviations for the books are specified in the config file.

OK, it should be the problem, as it is for the Vulgate I don't know exactly all the good abbreviations. I will complete the config file.

**Comment by adyeths** [comment]
Just in case you weren't aware, there is a Vulgate available at the [ebible.org](http://ebible.org/find/details.php?id=latVUC) site in a number of different formats, including usfm.

**Comment by LAfricain** [comment]
> Just in case you weren't aware, there is a Vulgate available at the ebible.org site in a number of different formats, including usfm.

Thank you for info, but I'm creating a new module for the vulgate (not the clementine one, but the older one) with all the missing books (deut and apocryphe).

> My next suggestion is to make sure all of the abbreviations for the books are specified in the config file.

Yes, this was the problem. Please add the info in the readme file. Solved again :)
