### ISSUE TITLE
USFM usage for a single chapter label marker before \c 1 and the resulting OSIS

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#53]
If you read carefully the **usage** note and the **examples** in the **USFM User Reference**,
it should become clear that when the `\cl ` tag is used once before `\c 1` then it's intended that in the formatted view, the chapter **number**  should be included in each subsequent chapter label.

![screenshot 2018-02-26 17 56 12](https://user-images.githubusercontent.com/16325414/36686529-9ef06844-1b1e-11e8-9eb4-461c3f6d8713.png)

With the latest commit of `u2o.py`, the chapter **number** is not appended to **n** attribute in the **milestone** element.
```
<div type="book" osisID="Gen" canonical="true">
<!-- mt --><title type="main">PRIMER LIBRO DE MOISÉS, LLAMADO COMUNMENTE GÉNESIS</title>
<chapter sID="Gen.1" osisID="Gen.1" n="1" />
<!-- cl --><milestone type="x-chapterLabel" n="CAPITULO" />
<verse sID="Gen.1.1" osisID="Gen.1.1" n="1" />En el principio creó Dios los cielos y la tierra.
```

Also, given that in the formatting example, each chapter label displays as a **heading**,
it prompts the question:  "Should the OSIS use a **title** element rather than a **milestone** element?"

**Comment by adyeths** [comment]
My tests show that there is no change in how the chapter label has been handled with my latest commits.

They look like this... `<milestone type="x-chapterLabel" n="CAPITULO 1"/>`

Whether it should be converted to a title rather than a milestone is a separate issue which has already been discussed. It will remain a milestone for the time being.

**Comment by DavidHaslam** [comment]
Your result matches what I got last week when the USFM looked like this:
```
\mt PRIMER LIBRO DE MOISÉS, LLAMADO COMUNMENTE GÉNESIS
\c 1
\cl CAPITULO 1
\v 1 En el principio creó Dios los cielos y la tierra.
```
and similarly for subsequent chapters.

My result today is for with the USFM like this:
```
\mt PRIMER LIBRO DE MOISÉS, LLAMADO COMUNMENTE GÉNESIS
\cl CAPITULO
\c 1
\v 1 En el principio creó Dios los cielos y la tierra.
```
The **n** attribute does not include the chapter number as I believe it should do.

NB. `CAPITULO` is simply the Spanish for `CHAPTER`.

Please read the usage note and example 1.

**Comment by adyeths** [comment]
I have uploaded some untested code to address this particular issue. It should work.

**Comment by DavidHaslam** [comment]
I just downloaded it and tested it.  I confirm that the issue was solved.

[RV1865.cl.search.results.txt](https://github.com/adyeths/u2o/files/1764484/RV1865.cl.search.results.txt)

Thanks once again, @adyeths 

David
