### ISSUE TITLE
Doesn't handle single chapter book with \c marker

### ISSUE THREAD

**Issue by RobH123** [adyeths/u2o#54]
I'm not sure about USFM3, but in USFM2 it was ok to not have a \c 1 marker in a single chapter book like Philemon. (Seems u2o currently gives something like Phm..1 in the OSIS.)

**Comment by adyeths** [comment]
I was not able to find anything in the documentation for usm to indicate that omitting the \c 1 marker was allowed in single chapter books. But it made sense to me to handle this situation anyway. I believe I have fixed this issue. I did a quick test on a bible I had by removing the `\c 1` marker in one of the books that has only one chapter. It worked and validated for me. Let me know if it works for you.

**Comment by RobH123** [comment]
Worked great.
