### ISSUE TITLE
Parentheses in parallel passage references \r_text

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#56]
Currently, `u2o.py` doesn't do anything with the **parentheses** usually found in a **parallel passage** reference.

Thus, taking the example in the USFM User Reference:
```
\r (Mark 1.1-8; Luke 3.1-18; John 1.19-28)
```
is converted to
```
<!-- r --><title type="parallel"><reference type="parallel">(Mark 1.1-8; Luke 3.1-18; John 1.19-28)</reference></title>
```
IMHO, it would make sense to move the **parentheses** to _outside_ the **reference** element:
```
<!-- r --><title type="parallel">(<reference type="parallel">Mark 1.1-8; Luke 3.1-18; John 1.19-28</reference>)</title>
```
This would leave the content of the **reference** element more amenable to being processed by `orefs.py`.

**Comment by adyeths** [comment]
When I get some time I will fix orefs to handle these references that are surrounded by parenthesis.

**Comment by adyeths** [comment]
orefs should be able to handle references surrounded by parenthesis now. Test it and let me know if it works ok for you.

**Comment by DavidHaslam** [comment]
Thanks!

I've not yet used `orefs.py`. It may be some time before I get the hang of it.

**Comment by LAfricain** [comment]
I tested on Konvb (Future kikongo release), it use also parenthesis, it runs perfectly with it. This issue can be closed according me.
