### ISSUE TITLE
Structured list entries - new markers defined in USFM 3.0 documentation

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#57]
**USFM 3.0** also introduced new markers for use within **Structured list entries**.

See https://ubsicap.github.io/usfm/lists/index.html

The new markers are **\lik_...\lik*** and **\liv#_...\liv#***

I think there is no coding for these yet in `u2o.py`

**Comment by adyeths** [comment]
Both of these tags are handled already.
