### ISSUE TITLE
Cosmetic: Only the first <description ...> element is indented in the OSIS file made by u2o.py

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#59]
See [screenshot](https://www.dropbox.com/s/6d9uih5c1snazyj/Screenshot%202018-12-15%2014.45.39.png?dl=0).

**Comment by adyeths** [comment]
This is the result of not using the pretty print feature that the script provides. No attempt is made to pretty print anything unless that option is used.
