### ISSUE TITLE
Add a command line option to specify the updated CrossWire OSIS schema?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#6]
Suggest add the option **-u CrossWire** to specify including the CrossWire _**u**pdated_ OSIS schema instead of the official one at Bible Technologies.

See https://crosswire.org/wiki/OSIS_211_CR#CrossWire_updated_schema

The argument should be _case-insensitive_ and should even permit _abbreviating_ to **CR**.

The _default_ should remain as the official schema.

**Comment by adyeths** [comment]
Adding special command line options for specific organizations would not be appropriate.

If a new official version of the osis schema is ever officially released, then I will update this script as needed at that time to use the new osis schema.

**Comment by DavidHaslam** [comment]
Unless of course one did it _indirectly_, using an **Internet Shortcut** in the same directory.

If one standardised the name of the shortcut, then only the **-u** option would be required.

It would become -u for **U**se the OSIS schema in the shortcut link.

This would make it entirely flexible, rather than being tied to a specific organization.

**Comment by DavidHaslam** [comment]
Or the schema URL could **always** be specified in an external text file which the user could edit as the need arises. This would obviate the need for a CL option.

**Comment by adyeths** [comment]
Trying to support the use of multiple versions of the osis schema would not be a simple task. The complexity of trying to do this would quickly spiral out of control making this script far more complicated than it was ever intended to be. This is not going to happen.

**Comment by DavidHaslam** [comment]
What's complicated about having one external text file with a single URL in it?

I'm not after multiple versions. Just support for **schema indirection**, to save novices having to edit the Python script themselves, and to save users always having to edit the fifth line in every OSIS file they generate.

Is that not a sensible requirement? It's eminently feasible without much hassle.
No danger of things "spiralling out of control" at all.

**Comment by adyeths** [comment]
It's more complicated than you realize. It's not as simple as just pointing to a different schema.

If people are using different versions of the schema then different things are going to be allowed in the conversion. This would make the simplicity of the dictionaries that I use in the conversion useless. I would have to completely refactor how that is done and use a completely different method to support the use of multiple ways tags could be converted. 

The built in validation would be rendered useless as well. This script doesn't fetch the schema over the internet when it validates the output. It uses the schema that is embedded in the script to validate the output. That would have to be done in a completely different manner as well.

The goal of this script is efficiency and speed in converting usfm to osis. Introducing unnecessary complication by trying to support multiple versions of the osis schema is not something I will ever be willing to do.

**This is not a change that is going to happen.**

**Comment by DavidHaslam** [comment]
Thanks for explaining in more detail.

Because I've generally left validation until later by using the **-x** option, this wasn't something I so readily appreciated.

I generally use the **XML Tools** plugin for **Notepad++** to validate the XML against the OSIS schema.
