### ISSUE TITLE
With last commits output file is empty

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#62]
I did a pull for the new update, and the new u2o.py gives an empty osis file (only header).
I used this command line:
` u2o.py -e utf-8 -o ~/Documents/gitlab/sword-modules/CPDV/sacredbible/osis/cpdv.osis.xml -v -d cpdv ~/Documents/gitlab/sword-modules/CPDV/sacredbible/usfm/01-GEN-ENG\[B\]CPDV2009\[pd\].p.sfm`
```
<?xml version='1.0' encoding='utf-8'?>
<osis xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd">
  <osisText osisIDWork="cpdv" osisRefWork="Bible" xml:lang="und">
    <header>
      <revisionDesc resp="cyrille">
        <date>2018.12.26T11.51.11</date>
        <p>Converted from USFM source using u2o.py</p>
      </revisionDesc>
      <work osisWork="cpdv">
        <title>cpdv</title>
        <type type="OSIS">Bible</type>
        <identifier type="OSIS">Bible.und.cpdv</identifier>
        <refSystem>Bible</refSystem>
      </work>
    </header>
  </osisText>
</osis>
```
Something change in the command line?

**Comment by DavidHaslam** [comment]
Aside: My command line is typically much shorter. 

Beforehand, I had made symbolic links to keep the paths short. e.g.

```
adyeths/u2o.py -l mg -x bible.mg1865 Malagasy/*.usfm
```

 I generally avoid using strange characters in the command line. 

Being a Windows user, I run such Python scripts in a Cygwin shell. 

David

**Comment by DavidHaslam** [comment]
I should add that I have yet to download the most recent commit. 

But when testing, it’s good to reduce a command line to something very simple.

**Comment by LAfricain** [comment]
No even with a short command line nothing in the output!!
 `u2o.py -x cpdv *.sfm` Need I to install some new python package?

**Comment by LAfricain** [comment]
I have integrated each modification one by one until I find the part that prevent to execute well the script, the wrong code for me is line 2917:
```
    filenames = []
    for _ in args.file:
        filenames.extend(glob.glob(_))
    args.file = filenames
    del filenames
```

**Comment by DavidHaslam** [comment]
I will therefore wait until this new bug is fixed.

**Comment by adyeths** [comment]
This should be fixed now. Test it and let me know.

**Comment by LAfricain** [comment]
Yes it runs again. But I have now this issue:
`Validation failed: line 1: b"Couldn't find end of Start Tag milestone line 1" (line 1)`
If I look in the osis output I have this extra tag `/>" />` 135 times in the file. I think the problem is with the \ca tag. Ex in osis:
```
<chapter sID="Ps.145" osisID="Ps.145" n="145" />
<!-- cl --><milestone type="x-chapterLabel" n="Psalm 145  <milestone type="x-usfm-ca" n="(146) " />" />
</div>
```
The problem is with all the psalms with a \ca \ca* tag and one time with Song1:
```
<chapter sID="Song.1" osisID="Song.1" n="1" />
<!-- cl --><milestone type="x-chapterLabel" n="Song of Songs 1<note placement="foot"><reference type="annotateRef">1:0 </reference>The first, fifth, and seventh chapters have been re-numbered so that each verse contains only the words of one particular speaker. <seg type="x-usfm-fl">(Conte)</seg></note><note placement="foot"><reference type="annotateRef">1:0 </reference>The labels of ‘Bride,’ ‘Groom,’ and ‘Chorus’ are not in the source text, and are added to clarify the meaning of the text. However, some labels might not apply to some levels of meaning of some verses. There is a spiritual level of meaning to the text in which the Groom is Christ, the Bride is the Church, and the Chorus is those who are not yet mature in the Faith. The bride is speaking about her desire for the groom. The pronoun ‘sui’ is singular masculine; it cannot be singular feminine; therefore, this is the bride speaking about the groom. The bride is the Church, who constantly seeks the love of the Christ and hopes for His blessings.<seg type="x-usfm-fl">(Conte)</seg></note>" />
```
