### ISSUE TITLE
Suggest provide a relaxed conformance option in the u2o command line

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#64]
I have a set of SFM files in which the translators had used:
```
\ide 65001 - Unicode (UTF-8)
```
instead of 
```
\ide UTF-8
```
NB. They were probably using an older version of ParaTExt when these were made.

For such situations, it might be preferable to permit relaxations to strict conformance for lines that have no semantic significance, this being one such example.

cf. All the SFM files were properly encoded as UTF-8.

Permitting relaxed conformance would obviate the need to preprocess all 66 files just to fix this niggle.

**Comment by adyeths** [comment]
Preprocessing is unnecessary in this situation. You can specify the encoding on the command line. I will add this particular way of specifying UTF-8 as valid though.

**Comment by DavidHaslam** [comment]
Thanks. It may be next week.
