### ISSUE TITLE
Detecting nesting errors in character level markup

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#65]
(I'm not sure the title is good)
When I try to convert:
```
\v 18 Njalo kwakwenziwe \w \add ng\add* amakherubhi\w**\x + 41.20,25; 1 Kho. 6.29,32,35; 7.36.\x* lezihlahla zelala, kuze kuthi isihlahla selala sasiphakathi kwekherubhi lekherubhi; njalo \add yilelo lalelo\add* ikherubhi lalilobuso obubili\x + 41.20,25; 1 Kho. 6.29,32,35; 7.36.\x*\x + 2 Lan. 3.5; 40.16,22,26,31,34,37; 41.26.\x*.
```
I have this result:
```
<verse sID="Ezek.41.18" osisID="Ezek.41.18" n="18" />Njalo kwakwenziwe <transChange type="added">ng</transChange> amakherubhi<index index="Glossary" level1="<transChange type="added">ng</transChange> amakherubhi" /><note type="crossReference">41.20,25; 1 Kho. 6.29,32,35; 7.36.</note> lezihlahla zelala, kuze kuthi isihlahla selala sasiphakathi kwekherubhi lekherubhi; njalo <transChange type="added">yilelo lalelo</transChange> ikherubhi lalilobuso obubili<note type="crossReference">41.20,25; 1 Kho. 6.29,32,35; 7.36.</note><note type="crossReference">2 Lan. 3.5; 40.16,22,26,31,34,37; 41.26.</note>.
<verse eID="Ezek.41.18" />
```
The xml error seems to be there:`"<transChange type="added">ng</transChange> amakherubhi" />`

Should be:
`<verse sID="Ezek.41.18" osisID="Ezek.41.18" n="18" />Njalo kwakwenziwe <transChange type="added">ng</transChange> amakherubhi<index index="Glossary" level1="amakherubhi" />*<note type="crossReference">41.20,25; 1 Kho. 6.29,32,35; 7.36.</note> lezihlahla zelala, kuze kuthi isihlahla selala sasiphakathi kwekherubhi lekherubhi; njalo <transChange type="added">yilelo lalelo</transChange> ikherubhi lalilobuso obubili<note type="crossReference">41.20,25; 1 Kho. 6.29,32,35; 7.36.</note><note type="crossReference">2 Lan. 3.5; 40.16,22,26,31,34,37; 41.26.</note>.
<verse eID="Ezek.41.18" />`

**Comment by DavidHaslam** [comment]
### Background: 

The USFM word level marker `\w ...\w*` is for marking words that are to be found in the associated glossary.

The second asterisk is one way in which some translators mark the word in the Biblical text such that in the **printed** edition, readers are informed that the tagged word is one that may be found in the glossary - which is typically supplied as an appendix.

_Of course, in a digital Bible module viewed by means of Bible software (not necessarily SWORD), the second asterisk may not be needed, as the programmer can devise other means to link the word in the Biblical text to the ancillary glossary module. e.g. By making the marked word a hyperlink._

**Comment by DavidHaslam** [comment]
The important point is this: 

- The second asterisk is simply part of the text. It's not part of the USFM markup.

**Comment by DavidHaslam** [comment]
btw. I have observed this usage in several Bible translations during the past decade.

**Comment by LAfricain** [comment]
Yes I know, but I have no idea from where come the issue :) Please suggest me a new title :)

**Comment by DavidHaslam** [comment]
Suggest: Parsing an optional extra asterisk immediately after a glossary word.

**Comment by DavidHaslam** [comment]
It's part of a wider issue, though unlikely to be seen in real life apart from with **Special features**:
`\w ...\w*`, `\wg ...\wg*` , `\wh ...\wh*`, `\ndx ...\ndx*` and the like.

Correctly parsing the end of word or character level markup when the next text character is an asterisk.

**Comment by adyeths** [comment]
There are two problems here that I can see, but they are unrelated to the extra asterisk.

1. Nested character styles in usfm are supposed to be preceded by a + which is missing here. u2o is currently not picky about this.
2. The extra markup for the nested tag is what appears to be causing the issue here. I will have to investigate this more.

**Comment by DavidHaslam** [comment]
Thanks - I'd failed to spot the nesting issue until you pointed it out.

i.e. The USFM for this line should become:
```
\v 18 Njalo kwakwenziwe \w \+add ng\+add* amakherubhi\w**\x + 41.20,25; 1 Kho. 6.29,32,35; 7.36.\x* lezihlahla zelala, kuze kuthi isihlahla selala sasiphakathi kwekherubhi lekherubhi; njalo \add yilelo lalelo\add* ikherubhi lalilobuso obubili\x + 41.20,25; 1 Kho. 6.29,32,35; 7.36.\x*\x + 2 Lan. 3.5; 40.16,22,26,31,34,37; 41.26.\x*.
```
or in brief, `\w \+add ng\+add* amakherubhi\w*`

NB. If the string `ng` is actually part of the vernacular word, there should be no space before `amakherubhi`, thus:
`\w \+add ng\+add*amakherubhi\w*`

Aside: GitHub Markdown requires a non-word character after the _italics_, so I can't show here how it should render.

All other locations with similar markup should be reviewed.

**Comment by DavidHaslam** [comment]
@LAfricain 

Please refer to USFM [Character Marker Nesting](https://ubsicap.github.io/usfm/characters/nesting.html).

Although there are no _examples_ in the USFM documentation that use these particular two types of markers nested, it's certain that they fall within the scope of character marker nesting.

**Comment by LAfricain** [comment]
Yes this new title is the right.

**Comment by DavidHaslam** [comment]
@LAfricain 
Did the validation fail at the same location?

Please record the OSIS fragment as well as the updated USFM line.

Are there any other similar locations which should have been changed as well?

**Comment by LAfricain** [comment]
Yes it is at the same place.

**Comment by DavidHaslam** [comment]
Is the **transChange** element within a **seg** element ?

Such a workaround is often the simplest way forward to fix this type of OSIS validation fail.

cf. Some OSIS elements do not allow **transChange** within them directly.

David

**Comment by DavidHaslam** [comment]
Looking closer at this issue, I can't see how **seg** would help at all for this narrow issue.

I wonder whether what's needed therefore is to strip the XML markup from the glossary **level1** attribute string within the **index** element.

So assuming there's no space in the vernacular word **ngamakherubhi** 
```
<transChange type="added">ng</transChange>amakherubhi<index index="Glossary" level1="ngamakherubhi" />
```
NB. The **index** element represents a point in the text and therefore does not allow any content, either text or elements.

**Comment by DavidHaslam** [comment]
This presupposes that the **index** element is the right thing for a glossary marked word to be converted to.

I think we ought to compare what `u2o` does with what other scripts do here.

Especially the latest version of `ufsm2osis.py` developed by **JohnAustinDev** in his **Module-tools**.

cf. Many of the Bible modules he is also responsible for have words that are linked to a glossary

**Comment by DavidHaslam** [comment]
This example shows how **JohnAustinDev** handles a glossary link:
```
<reference osisRef="UZVLDICT:XUDONING_32_RUHI" type="x-glossary">Xudoning Ruhi</reference>
```

- That's the first glossary marked word in module UZVL, and is found in Genesis 1:2
- The module contains 19330 such references of this type.
- There are only 186 distinct glossary entries thus referenced from the Bible module.
- Glossary module UZVLDICT is specified as a companion module within uzvl.conf

**Comment by DavidHaslam** [comment]
NB. An **osisRef** for such a glossary entry cannot contain any space or punctuation mark (other than the colon that delimits the **workID**), therefore
- `_32_` is used to encode a space
- `_44_` is used to encode a comma

**Comment by DavidHaslam** [comment]
It's valid USFM, in the sense that there's nothing in the documentation to suggest otherwise.

Clearly, there are several languages in which the grammar is such that _parts of words_ are sometimes required to be added by the translators, whether as a _prefix_ (as in this African language) or as a _suffix_ (such as with **enclitics** in Spanish).  See https://en.wikipedia.org/wiki/Clitic

That the resulting word might also need to be a glossary entry is not something the OSIS committee ever imagined or considered.

IMHO, the OSIS documentation sometimes falls short of being helpful for current usage in the light of  developments in the SWORD API and front-ends that post-date the OSIS 2.1 standard. For this reason, although `index` might have been seen as the sensible way to convert `\w ...\w*` when OSIS 2.1 was released, the OSIS committee would not have been in a position to anticipate how glossaries would be developed in Bible software applications.

I can well understand your difficulty about how to handle it.

**Comment by DavidHaslam** [comment]
The Ndebele word **ngamakherubhi** does occur without any space between `ng` & `amakherubhi`. See 

https://bibledit.org:2001/exports/NdebeleTeam/web/02-Exodus-026.html

And there's an asterisk in this Bibledit view, such that it's a word that was tagged for the glossary.

This example in **Exodus 26** (without using `\add ...\add` to wrap the `ng`) shows that the glossary entry really is **ngamakherubhi** and explains how and why **Ezekiel 41:18** references the same glossary word.

**Comment by DavidHaslam** [comment]
AFAICT,  `ng` is a very common **proclitic** in Ndebele and other Bantu languages.

**Comment by DavidHaslam** [comment]
@adyeths 

I have put the question to ICAP in this [issue](https://github.com/ubsicap/usfm/issues/78).

**Comment by DavidHaslam** [comment]
@adyeths 

With so much water under the bridge since OSIS 2.1.1 was published, the **index** element is no longer the correct choice when the USFM `\w ...\w*` marker is used with **Word Level Attributes** such as Strong's numbers. 

In OSIS, Strong's numbers are coded as attributes of the **w** element.

This requires much more detailed consideration, and is beyond the scope of this current issue.

See also #3

**Comment by adyeths** [comment]
The index element is the correct element in this particular instance.

I have not ignored the new word level attributes. They are handled just fine. When strongs numbers are present the proper osis tags are created.

**Comment by adyeths** [comment]
I have added a special filter for the transChange element in this situation. Test it and let me know if it works for you. (Note that this special filter will require using the correct usfm nested tag syntax.)

**Comment by LAfricain** [comment]
No the problem remains :+1: 
```
<verse sID="Ezek.41.18" osisID="Ezek.41.18" n="18" />Njalo kwakwenziwe <transChange type="added">ng</transChange>amakherubhi<index index="Glossary" level1="<transChange type="added">ng</transChange>amakherubhi" />*<note type="crossReference">41.20,25; 1 Kho. 6.29,32,35; 7.36.</note>
```

**Comment by adyeths** [comment]
You didn't use the nested tag syntax. (with the + in the usfm tag). While u2o is still not picky about that, the fix I implemented in orefs is picky about it.

**Comment by LAfricain** [comment]
Yes you are right! Now I need to find all af it...
