### ISSUE TITLE
Orefs.py doesn't generate references

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#68]
After generating well the config file, named in this case RefNd, I run orefs.py but nothing is generating:
orefs.py -v -i ndebele.osis.xml -o ndebele.osis.ref.xml -c RefNd
Terminal returns:
```
...
WARNING: Reference not processed… Rev 6.
WARNING: Reference not processed… Rev 1.
WARNING: Reference not processed… Dute. 4.2.
WARNING: Reference not processed… Eks. 32.33.
WARNING: Reference not processed… Rev 5.
WARNING: Reference not processed… Rev 2.
WARNING: Reference not processed… Rev 7.
WARNING: Reference not processed… 2 Tim. 4.8.
WARNING: Reference not processed… Rom 24.
...
```
Maybe because all ref ends with a period? Like that: Hlab. 41.13. or 16.41. Hlab. 106.1. 107.1. 118.1. 136.1.
I have the same issue with Turntb, but in this case the ref are sticked like that:  `<reference osisRef="">Mat.19:4-5; Mar.10:7-8; 1Ko.6:16; Ef.5:31<!-- orefs - unprocessed reference --></reference>`

**Comment by LAfricain** [comment]
For Turntb it is ok, I added a period after the book name in the config file and it works.

**Comment by LAfricain** [comment]
I found the problem. Orefs doesn't recognize the period after the between the chapter and the verse. The config file is OKAY, with `SEPC = .`.
But what is strange, is, if I try to change some refs for test, using the ` :` instead of a period, and with the same config file, the ref are well converted.

**Comment by LAfricain** [comment]
Even now, the problem subsist:
`<reference osisRef="1Kgs.29.45 1Kgs.26.11">2 Mos. 29,45. 3 Mos. 26,11.<!-- orefs - unprocessed reference --></reference>`
If it not possible to manage it I can change all the refs?

**Comment by adyeths** [comment]
It looks like orefs thought there was more than 2 references here and that's why it added an unprocessed reference marker. (This particular issue should be fixed. I added a check to make sure when it sees empty references that it ignores them, such as appears happened here.)

**Comment by LAfricain** [comment]
It's not yet fix. It seems that orefs don't recognize the period as chapter and verse separator.
```
<reference osisRef="Rom.16.20">Roma 16.20,24.<!-- orefs - unprocessed reference -->
```
Or:
```
<reference osisRef="">21.2.<!-- orefs - unprocessed reference -->
```
or:
```
<reference osisRef="">Eks. 32.33.<!-- orefs - unprocessed reference --></reference>
```
You can see the only place where orefs create a ref is the place with a comma. The config file seems to be OK:
```
SEPM = ;
SEPP = ,
SEPC = .
SEPR = -
SEPRNORM = –—
DIGITS = 0123456789
```
If you want to test, the attach file is Genesis in usfm:
[03_Genesis.zip](https://github.com/adyeths/u2o/files/2824194/03_Genesis.zip)

**Comment by adyeths** [comment]
it's getting confused because you're using a period to separate chapter and verse as well as multiple references. I don't know of any way to make that work.

**Comment by LAfricain** [comment]
Yes you are right,  it use a period to separate multiple refs,and  a semi column to separate multiples refs of the same book following!! But it should almost run for the single refs.

**Comment by DavidHaslam** [comment]
Before using `orefs.py`, there's clearly a requirement to perform some preliminary analysis of all the references in an OSIS file. I can readily use a bespoke **TextPipe** filter to extract all references but not everyone uses Windows, let alone has a copy of TextPipe.

It would be useful to have an ancillary Python script for just this task.

The output data could be in **tab delimited text** format, with field 1 containing the current location's **osisID** and field 2 containing the unprocessed reference string.

Presenting them in such an uncluttered format would aid the user to identify which reference strings have inconsistent punctuation, spacing or even spelling.

The command line might even have an option:
`-s ` would attempt to separate reference strings into separate references using the SEP punctuation from the same config file.

**Comment by adyeths** [comment]
in order for orefs to process a reference that looks like this `Eks. 32.33.` the period at the end has to be removed. If that can't be done, then the references will have to be manually fixed after running orefs.

**Comment by LAfricain** [comment]
Now, I change the SEPM = ; SEPP = , SEPC = : in the input file, I removed the periods that end the refs lines, and change the period separating multiples refs with semi-column but it doesn't work anymore:
```
<reference osisRef="Gen.3.4">3:4; 2 Kor. 11:3; 1 Tim. 2:14<!-- orefs - unprocessed reference -->
```
I'm sure the problem is the period that ends the book names, look if you don't have a book that ends with a  period it works perfectly:
```
<reference osisRef="Gen.2.18 Job.31.33">2:18; Jobe 31:33</reference>
```
Thanks for you patience :)

**Comment by adyeths** [comment]
is the period included in the abbreviations in the conf file?

**Comment by LAfricain** [comment]
You speak about the period that ends the book name? If this yes it is.
```
Gen = UGenesise, Gen
Exod = UEksodusi, Eks.
Lev = ULevi, Levi
Num = Amanani, Nani
Deut = UDuteronomi, Dute.
Josh = UJoshuwa, Josh.
Judg = Abahluleli, Hlu.
Ruth = URuthe, Ruthe
1Sam = 1 USamuweli, 1 Sam.
2Sam = 2 USamuweli, 2 Sam.
...
```
Need I to remove it?

**Comment by adyeths** [comment]
If the abbreviations that are used include the period, then it has to be included in the conf file. Otherwise it won't work. As for why these references aren't being processed, I really have no idea what's going on.

**Comment by adyeths** [comment]
Since this issue seems to be the same as #77 then there's no point keeping this one open... so I will close this one and try to investigate that other one further.
