### ISSUE TITLE
\\sp tag

### ISSUE THREAD

**Issue by refdoc** [adyeths/u2o#69]
\\sp is currently handled wrongly I think - the resultant <speaker> </speaker> tag set encompasses everything in the subsequent speech. Both USFM handbook and OSIS handbook suggest that the spe aker tag/\\sp is used in a very limited form , more like a title element or some such

\sp Bride:
\v # bla bla bla
`<speaker>Bride:</speaker>`
`<verse...>Bla bla bla</verse>`

**Comment by adyeths** [comment]
This should be fixed now. Test it and let me know.
