### ISSUE TITLE
Make the default filename <workid>.osis.xml instead of just <workid>.osis

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#7]
Many developers will already have the file extension **.xml** associated with an application or a text editor.
Fewer will have the file extension **.osis** thus associated in Windows.

IMHO, it would be preferred therefore to make the default filename `<workid>.osis.xml`

**Comment by adyeths** [comment]
After thinking about this I've decided that, _for now_, I'm not going to do anything with this. There are several reasons.

1. This seems like more of a personal preference to me than anything else. And I personally prefer that the default is not to have the .xml extension on the filename.
2. Associating the osis extension with a text editor is a pretty trivial thing that would only need to be done once.
3. There is already a mechanism in place to specify file naming that would allow for any file name and extension to be used.

If there is more demand for this change then I will reconsider. I would have to hear from more people about this though. _For now_ I will leave the default naming as it is.

**Comment by DavidHaslam** [comment]
Counter to those arguments is that many users would already have a file association for the .xml extension and it would seem somewhat tedious to make an exception for "yet another kind" of XML called OSIS.

But as you say, it's still a fairly trivial matter, and it could well be deemed a personal preference.

I've just associated .osis with Notepad++ and it works fine.

**Comment by alerque** [comment]
This is one ugly side of XML being a catch-all format. The assumption you're making @DavidHaslam is that users will want to use the same viewer/editor for all XML files. In my experience this might be the case for folks that don't know much about XML in the first place, but for developers that push around a lot of data files this is often not the case. I have several different XML based formats set open in different editors. This is easy to do when they have extensions that match their scheme and much harder when they don't. In some cases I'm either filtering by location (projects under X directory get different defaults than elsewhere) or sniffing the data by reading the first few lines to figure out what to open them with. This is a hassle that could easily be avoided using an extension per the schema.

This is not without precedent either. You wouldn't really want all your SVG graphic files opening in Notepad++ would you? Sure you _could_ open them there, but chances are you're rather have those open in a vector graphics viewer/editor. Likewise you wouldn't want Word's DOCX or LibreOffice's ODT files opening in Notepad++ would you? These are XML based formats but they follow a specific schema and those schemas are usually best handled by their respective programs.

Using `.osis` makes it easy to setup your system to use your preferred OSIS reader. It also makes build pipelines easier to manage. This is my primary concern with OSIS files but it's really just an extension of the same issue.

**Comment by LAfricain** [comment]
My preference is too "osis.xml" (I change it for me).

**Comment by DavidHaslam** [comment]
I've recently added `.osis` as an associated file extenstion for **Notepad++**.

Closing the issue.  No further action required.
