### ISSUE TITLE
Unusual punctuation method for reference ranges

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#70]
### Observation FYI

One project I'm working on has 9 of the 331 parallel passage headings with two hyphens as the range specifier.
```
Count	Reference
------	-----------
000001	Ef. 5:22--6:9
000001	Kol. 3:18--4:1
000001	Mar. 2:23--3:6
000001	Mar. 8:31--9:1
000002	Mar. 8:34--9:1
000001	Yoox. 18:26--19:16
000001	Yoox. 18:33--19:16
000001	Yoox. 18:39--19:16
```

- These are all cases where the range crosses a chapter boundary.
- cf. All the other range references use a single hyphen.

**Comment by LAfricain** [comment]
Maybe a workaround only for o2refs.py is to replace -- with -.

**Comment by DavidHaslam** [comment]
Except that would be changing the translators’ text - which we aim to avoid - especially when it’s copyright.

**Comment by adyeths** [comment]
try adding this to the SEPRNORM variable at the top of the config file. (The list has 2 entries by default. add a third "--")

**Comment by adyeths** [comment]
This should be fixed now. Test it and let me know.

**Comment by DavidHaslam** [comment]
I’m not yet at a stage in that project where I can test it. 

Plus I’m working on several other projects that are occupying a lot of my time.
