### ISSUE TITLE
orefs.py error when reading refs of the same book

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#71]
When  o2refs.py, reads for instance: Mat.15:4; 19:19, it should understand Mat 19:19 for the second ref, but it reads it as ref of the current book. By instance if this ref 19:19 is in Deut, it will write Mt 15:4 and Deut 19:19.

**Comment by LAfricain** [comment]
If a partial reference is preceded by a semicolon, it should be understood as belonging to the complete reference which precedes it. If not then understood as belonging to the current book.

**Comment by DavidHaslam** [comment]
Assuming that the **semicolon** is configured as the punctuation mark allocated for separating references in a string of several references. 

It's typically a semicolon for those of us used to languages written in a Latin script, yet it could be quite a different character for some non-Roman scripts and/or RtL scripts.

Not to mention the quirks of particular translators to muddy the waters.

**Comment by DavidHaslam** [comment]
Rather : The **last** complete reference that preceded it.

**Comment by LAfricain** [comment]
Yes :)

**Comment by adyeths** [comment]
If you replace the `;` with a `,` (or whatever SEPP happens to be set to in the conf file) then orefs will be able to process the reference as you intended. (`Mat.15:4, 19:19`)

It is unlikely that I will be able to make orefs handle bookless references that are intended to refer to the current book being processed as well as bookless references that are intended to refer to the book in the last complete reference that was processed.

**Comment by DavidHaslam** [comment]
@adyeths

It is feasible. It’s just more difficult. Please don’t give up. :)

**Comment by DavidHaslam** [comment]
If there is no [preceding] complete reference, then a partial reference can **only** refer to the current book or chapter. 

If there is a [preceding] complete reference, then a partial reference is to be implicitly understood as referring to the same book or chapter as in that reference. 

If there is a [preceding] bookless reference that has already been resolved, a chapterless verse would refer to the same chapter that was in that resolved reference. 

It’s really a matter of listing all the eventualities that have to be considered. 

These points remain valid even when there is totally consistent punctuation. 

A corner case with extra complexity is when the previous complete reference is to a range than spans across the end of a chapter.

**Comment by DavidHaslam** [comment]
Translators’ typos also provide the opportunity for impossible references such as Oba 2:5 or (more likely) Jud 6:5 where Jud is the abbreviation for Jude that the translator mistakenly wrote when he meant Jdg for Judges (or even Jdt for Judith).

To detect impossible references is beyond the scope of `orefs.py`.

**Comment by LAfricain** [comment]
>If there is no [preceding] complete reference, then a partial reference can only refer to the current book or chapter.

Yes. This works good I think.
>If there is a [preceding] complete reference, then a partial reference is to be implicitly understood as referring to the same book or chapter as in that reference.

Yes, this should be right, but we only can be sure if the ref is preceded with a comma, but if it is with a semicolon it is ambiguous. Ex: on Turkish 2Kgs.20.1 : `2Ta.32:24-26; Yşa.38:1-8; 21-22` You have a semicolon and 21-22. I doubt it is Ysa (Isaie), because it should precede `38:1-8` but finally it can. `2Kgs22.1: 2Ta.34:1-2; 8-28`, same problem, but now I can image it is really 2Ta (2chr.)

Perhaps I am completely mistaken and all the references that follow a semicolon are a good match to the preceding reference. For that, one should carefully analyse the references in question. To be honest, it seems credible, but I have some doubts...

>If there is a [preceding] bookless reference that has already been resolved, a chapterless verse would refer to the same chapter that was in that resolved reference.

Yes this is ok.

**Comment by DavidHaslam** [comment]
The two instances from TurNTB are both number ranges occurring after a previous complete reference (albeit also both happen to be a range).

How to you determine whether it’s a verse range or a chapter range?

If the translator really intended for the reference to be to the current book and chapter, he really ought to have placed them at the start of the string. Then it could only be a verse range. 

(A typo involving a single punctuation mark is much more likely than a misplacement of a group of characters.)

But what if he intended (e.g.) to mean chapter 21 to 22 of 2Kgs, which makes better sense given the current context is verse 1 of 2Kgs.20 ?

Had he placed it at the start, we could wrongly take them as a verse range in chapter 1 when he meant a chapter range. 

Yes - there are always going to be corner cases that are very hard to resolve. 

Understanding theses corner cases sheds a lot of light on the programming challenge.

**Comment by LAfricain** [comment]
I'm just surprise to discover, that sometimes, orefs work well on our situation, look:
```
  <p><verse sID="Gen.3.1" osisID="Gen.3.1" n="1"/><note type="crossReference"><reference type="annotateRef" subType="x-origin" osisRef="Gen.3.1">3:1 </reference><reference osisRef="Rev.12.9 Rev.20.2">Va.12:9; 20:2</reference></note>
```
But here no:
```
<verse sID="Gen.9.4" osisID="Gen.9.4" n="4"/><note type="crossReference"><reference type="annotateRef" subType="x-origin" osisRef="Gen.9.4">9:4 </reference><reference osisRef="Lev.7.26-Lev.7.27 Gen.17.10-Gen.17.14 Gen.19.26 Deut.12.16 Deut.12.23-Deut.12.25 Gen.15.23">Lev.7:26-27; 17:10-14; 19:26; Yas.12:16,23-25; 15:23</reference></note>
```

I I looked closely up the book to 2 kings, and It's clear that all refs following a semicolon are of the book on the preceded ref.

**Comment by LAfricain** [comment]
I noticed still that it is all the Rev ref that are good treated by orefs. I never found an issue with Rev!
