### ISSUE TITLE
\xo should not be converted to type="annotateRef"

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#72]
I'm just asking if the \xo tag currently convert like that:
`<reference type="annotateRef" subType="x-origin">`
Should be convert like that:
`<seg type="x-usfm-xo">`
Because, if we choose the first way, it will cause issue when using o2refs.py, all the `type="annotateRef"` will be converted as OSIS reference.
For this reason I proposed to use an other osis tag.

**Comment by DavidHaslam** [comment]
The `\xo ` tag is an **origin reference** for the [string of] references in the reference text,
It points back to the location where the cross-reference note or parallel passage heading or even an `\+xt reference\+xt*` almost anywhere might be found.

When the full text of the cross-reference note is displayed in (e.g.) the **Preview pane** of Xiphos, the reference after the `\xo ` tag is usually shown as a hyperlink that points back to the location where the note is.

The note text can remain displayed in the preview pane even after the user navigates to a different passage in the module.  Clicking the origin reference in the preview pane should cause module in the main window to jump back to the location in the text where the cross-reference note originated.

So IMHO, it is correct to use `<reference type="annotateRef" subType="x-origin">`.

I hope this explains adequately.

NB. The same logic also applies to the optional `\fr ` tag that can be used in USFM footnotes.

**Comment by LAfricain** [comment]
Ok I understand, thanks for explanation.
