### ISSUE TITLE
Making linked references in book introductions?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#76]
Here's part of a **book introduction**:
```
\iot Ана Хатлар:
\io1 \ior 1:1–2:25\ior* Евренин ве инсанън яратълъшъ
\io1 \ior 3:1-24\ior* Гюнахън ве аджъ чекменин башлангъджъ
\io1 \ior 4:1–5:32\ior* Адем'ден Нух'а
\io1 \ior 6:1–10:32\ior* Нух ве Туфан
\io1 \ior 11:1-9\ior* Бабил Кулеси
\io1 \ior 11:10-32\ior* Сам'дан Ибрахим'е
\io1 \ior 12:1–35:29\ior* Илк аталар: Ибрахим, Исхак, Якуп
\io1 \ior 36:1-43\ior* Есав'ън сойу
\io1 \ior 37:1–45:28\ior* Йусуф'ла кардешлери
\io1 \ior 46:1–50:26\ior* Исраиллилер Мъсър'да
\ie
```
Does `orefs.py` already process these **ior** references?

It would be a useful if such **introduction outline reference ranges** could be made into linked references in OSIS such that the user can click on one of these and jump straight to the passage start.

This example is for the book of **Genesis**, so all the references are to a passage in this book.

There could be similar items such as _chapter summaries_ containing **verse numbers**, where the same enhancement would be beneficial. How should such verse numbers be tagged in USFM ?

**Comment by adyeths** [comment]
orefs will try to process any bible references it finds. Those it can't process are flagged. chapterless references are not processed and will need to be handled manually.
