### ISSUE TITLE
All refs without name with only chap and verse are convert as Rev.

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#78]
All is in the title, ex:
```
<reference osisRef="2Kgs.13.23 Rev.24.20 Ps.51.11 Jer.52.3">2 Kho 13:23; 24:20; Hlab 51:11; Jer 52:3
```
You see 24:20 should be convert to 2kings, but it is convert as Rev!
Other places:
```
<reference osisRef="Gen.8.21 Job.14.4 Rev.15.14 Ps.51.5 Jer.17.9 Matt.15.19 Rom.3.23">8:21; Jobe 14:4; 15:14; Hlab 51:5; Jer 17:9; Mat 15:19; Roma 3:23
<reference osisRef="Ezek.8.17 Rev.9.9 Rev.28.16">Hez 8:17; 9:9; 28:16</reference>
```
All this refs are in the book of Genesis. It is clear that the refs without book names following a refs with a book name, belongs to this book.

**Comment by DavidHaslam** [comment]
I've not yet really started to ascend the learning curve for `orefs.py` being occupied on other tasks.

However, if the above illustration is what it does, then there is a serious error besides what @LAfricain reported.

You simply shouldn't have just a single reference element.

- Each reference string should be wrapped within it's own reference element.
- Each reference element should have an osisRef attribute with a single reference or a range.
- Characters that are not part of a reference (e.g. punctuation between references) should be outside the reference elements.

**Comment by adyeths** [comment]
@LAfricain Change the `;` to a `,` (or whatever SEPP happens to be set as) for the references in the same book and the references should be converted properly.

@DavidHaslam orefs doesn't do anything other than insert osisRef attributes into reference elements. that's it. if you want references to be separated in the manner in which you describe, then the usfm markup will have to be changed accordingly.

**Comment by adyeths** [comment]
There are no such requirements specified in either the osis schema or the osis manual. I am not going to impose restrictions on the osis that I generate that are not specified.

**Comment by LAfricain** [comment]
> Change the ; to a , (or whatever SEPP happens to be set as) for the references in the same book and the references should be converted properly.

I change it, but now it refuse to convert  it ONLY if it is at the begin of the refs list. Look:
```
reference osisRef="Luke.1.6 Rom.2.13 Rom.3.19">7:1, 10:9, 13:13; Luka 1:6; Roma 2:13, 3:19<!-- orefs - unprocessed reference -->
```
If it is to an other place it runs well:
```
<reference osisRef="Exod.20.11 Exod.31.17 Deut.5.14 Heb.4.4">Eks 20:11, 31:17; Dute 5:14; Heb 4:4
```
If I have just one refs that begin the list of ref, it is okay.

**Comment by adyeths** [comment]
@LAfricain I will have to investigate this more to see if I can get it to work in this situation. In theory it should use the current book being processed there. Apparently it's not working as intended.

@DavidHaslam What you're discussing is unrelated to LAfricain's issue. Start a new issue if you want to discuss it further.

**Comment by LAfricain** [comment]
@adyeths Ok thanks.
@DavidHaslam You were asking me? → Xiphos Bibletime and AndBible.

**Comment by DavidHaslam** [comment]
I will add a new issue. 

The front-end question was for adyeths.
