### ISSUE TITLE
Restrict converting // to not within \rem text

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#8]
**u2o.py** quite happily converts a **URL** within a USFM remark line such that it ends up with the unwanted **optional line break**!

The conversion of **//** needs to be restricted to exclude locations within **\rem text**

Please review and improve this part of the code.

        if r'//' in text:
            text = text.replace(r'//', '<lb type="x-optional" />')

**Comment by alerque** [comment]
Crosslink commit that looks like it was intended to address this issue: c84f35fd6ddabf5a82fd3106f3c345b4b08ac30c
