### ISSUE TITLE
u2o.py - please support \mt5 tags

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#81]
Currently `u2o.py` can convert `\mt4 .....` but not `\mt5 .....`.

Admittedly `\mt5 ` is rarely used. 

_The enhancement is desirable though not urgent._

**Workaround:** I simply changed the SFM file for FRT matter to use `\mt4 ` in three places.

If and when you implement this, please review any similar tags that could have # extended to 5 too.

**Comment by DavidHaslam** [comment]
## Example
```
\mt5 The
\mt1 New Testament.
\mt5 translated from the
\mt3 original Greek,
\mt5 by
\mt3 H. T. Anderson.
```

**Comment by adyeths** [comment]
Done.
