### ISSUE TITLE
USFM \rem lines and OSIS p elements?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#83]
I think something strange happens
```
\v 4 It can not be. But let God be true, though every man be a liar, as it is written: That thou mightest be justified in thy words, and mightest overcome when thou art judged.
\p
\rem The phrase "God’s plan of justifying men" is not found in the 1866 printing.
\v 5 But if our unrighteousness causes the righteousness of God to be better known, what shall we say? Is God unrighteous, who inflicts punishment? I speak as a man.
\v 6 It can not be: for if so, how shall God judge the world?
\p
```
gives OSIS as follows: (after the rem line is extracted to the OSIS header)
```
<verse sID="Rom.3.4" osisID="Rom.3.4" n="4" />It can not be. But let God be true, though every man be a liar, as it is written: That thou mightest be justified in thy words, and mightest overcome when thou art judged.
</p>
<p>
<verse eID="Rom.3.4" />
</p>
<verse sID="Rom.3.5" osisID="Rom.3.5" n="5" />But if our unrighteousness causes the righteousness of God to be better known, what shall we say? Is God unrighteous, who inflicts punishment? I speak as a man.
<verse eID="Rom.3.5" />
<verse sID="Rom.3.6" osisID="Rom.3.6" n="6" />It can not be: for if so, how shall God judge the world?  <p>
<verse eID="Rom.3.6" />
```

Here's the **strangeness**:  Where did the extra `</p>` & `<p>` come from?
- I thing this may be a bug in `u2o.py`. 

btw. There were 3 similar occurrences in the project I was working on.

**Comment by adyeths** [comment]
usfm \rem tags are introduction tags, not general purpose comment tags. (Although, I know they are sometimes misused as general purpose comment tags.) That's why there is unexpected behavior being observed here. The rem tag gets moved to the header like the osis manual says to do and then there is leftover unexpected paragraph tags.

**Comment by DavidHaslam** [comment]
Understood, thanks.

I've therefore moved my \rem line[s] to the head.
_I will try and remember this is future._
