### ISSUE TITLE
periph element attributetext when there is none?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#84]
These lines (1473-1477) of code: 
```
                if attributetext is not None:
                    attributetext = '{}{}{}'.format(
                        '<!-- USFM Attributes - ',
                        attributetext,
                        ' -->')
```
produce this when there is no attribute text:
```
<!-- USFM Attributes -  -->
```

Although this is merely an XML comment, I still think that logically, the hyphen and 2 spaces should not be included when there's no attributetext. It should produce simply:
```
<!-- USFM Attributes -->
```

**Comment by adyeths** [comment]
What is the usfm that resulted in this?

**Comment by DavidHaslam** [comment]
Henry T. Anderson's 1864 "Civil War" New Testament https://github.com/BeTheLight/ENG-B1-Anderson1864-pd-USFM

_It’s what I’m currently engaged with. _

**Comment by DavidHaslam** [comment]
It’s obviously trivial inasmuch as it’s in the remark. 

I spotted it almost in passing while I was locating spurious instances of ` - `

**Comment by adyeths** [comment]
which file specifically produced this? Because there shouldn't be any empty attributetext comments like this.

**Comment by DavidHaslam** [comment]
One of the files has `00` in the file name. 

It’s either that or the next one with `40` in the filename. 

Apart from the last file with `69` all the others have the USFM standard NT numbering `41` through `67`.

_Wasn’t this almost intuitive?_

**Comment by adyeths** [comment]
I don't have any context with regards to where the problem with the attributetext occurred. That's what I'm trying to find. Without that context I can't determine why it happened when the code in question was written specifically to avoid putting random empty comments in the osis output.

If I knew where in the usfm files it happened, I could look at it and see why and possibly fix it.

**Comment by DavidHaslam** [comment]
Only two instances of `\periph ` as far as I can recall. 

These are in one of those small files at front or back of the NT. 

My PC is in sleep mode at this time of night, so I’m replying from memory.

**Comment by DavidHaslam** [comment]
I have given the context. 

I responded last night from memory as soon as you asked. 

Please re-open the issue. 

I can add more details once I’m at my workstation.

**Comment by DavidHaslam** [comment]
The fact that the issue title starts with the word periph is also to give the context. 

There are no instance of `\periph ` in files for MAT to REV.

**Comment by adyeths** [comment]
It should be fixed. Thats why I closed it.

**Comment by DavidHaslam** [comment]
Ah - sorry. 

I just saw “closed” after the notified previous comment. 

Aside: I’m writing from my iPhone using the CodeHub app. 

I hadn’t yet spotted that you’d committed a change.

**Comment by DavidHaslam** [comment]
Is there a related push ?

Or is it still in your pipeline?

**Comment by adyeths** [comment]
last commit should fix this.

**Comment by DavidHaslam** [comment]
Fix tested and confirmed.  _Many thanks_.
