### ISSUE TITLE
Critical XML errors in output

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#85]
I just used `u2o.py` to convert the USFM files for a **Belarusian** translation.
* cf. The OSIS for SWORD module **Bela** was made years ago using `usfm2osis.pl` & further processing.

Something is critically wrong in the XML output for **Psalms**. 
* `</title>` was inserted into verse milestone attributes!  
* This happened for all three attributes in 87 verses.

### Example:
```
<verse sID="Ps.10</title>.1" osisID="Ps.10</title>.1" n="1" />На Госпада спадзяюся; як жа вы кажаце душы маёй: "<transChange type="added">Як </transChange> птушка ўзьляці на гару вашу"?
<verse eID="Ps.10</title>.1" />
```
Attached Zip files provided for testing.
#### USFM
[19-psalm.txt.usfm.zip](https://github.com/adyeths/u2o/files/2872786/19-psalm.txt.usfm.zip)
#### OSIS
[Psalms.Bela.osis.zip](https://github.com/adyeths/u2o/files/2872788/Psalms.Bela.osis.zip)

##### Notes:
* When I omit the USFM file for Psalms, the OSIS for the remaining 65 books validates.
* The USFM file for Psalms contains multiple contextual `\rem ` lines.
* The files were edited in 2014 - so years before you pointed out that the `\rem ` tag is reserved for the USFM "header" - before the beginning of textual content.
* Even so, such a minor departure from the USFM standard should not lead to critical XML errors like this.

**Comment by DavidHaslam** [comment]
I have therefore also requested clarification from **UBSICAP** regarding the placement of `\rem` in context.

See [issue 83](https://github.com/ubsicap/usfm/issues/83).

**Comment by DavidHaslam** [comment]
Further symptoms:
```
<chapter sID="Ps.25</title>" osisID="Ps.25</title>" n="25</title>" />
```
In this instance, the XML artefact is within the attribute in the chapter milestone!

There were 24 such insertions in addition to those within verse milestones.

**Comment by DavidHaslam** [comment]
Even if the `</title>` artefacts are all removed, the XML is still not right.
* Some of the `div` elements in **Psalms** are not closed.

Thus the critical XML error is not merely the insertion of the `</title>` artefact in the wrong places, but the omission of `</div>` in several places.

**Comment by DavidHaslam** [comment]
Even if the `\rem ` lines are all removed from the SFM file for Psalms, the resulting OSIS file still has XML errors.

[PsalmsX.Bela.osis.zip](https://github.com/adyeths/u2o/files/2873074/PsalmsX.Bela.osis.zip)
* The **acrostic titles** `\qa ....` are not processed aright. 
* Might this be due to the absence of other poetry markup?

**Comment by DavidHaslam** [comment]
Looks like the absence of anything that would trigger the start of a poetry **line group** now causes the incorrect processing of acrostic titles.

**Comment by DavidHaslam** [comment]
### Significant observations:
* Inserting `\b` after each `\qa title` does not prevent the XML errors!
* Inserting `\q` after each `\qa title` prevents the XML errors.

**Comment by adyeths** [comment]
This had nothing to do with \rem lines. Issue is fixed.
