### ISSUE TITLE
Suppress screen msg "Use orefs to add osisRef attributes to references."

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#86]
In the screen message after `u2o.py` has done its stuff, you may wish to temporarily suppress the second line that reads "Use orefs to add osisRef attributes to references."

i.e. While this is not being maintained.

**Comment by DavidHaslam** [comment]
Whether to offer any suggestions at all is something for you to decide.

**Comment by adyeths** [comment]
done
