### ISSUE TITLE
Acrostic titles (qa tag) still not right - title text now placed after </title>

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#87]
The latest "fix" didn't work out right.  
```
<!-- d --><title type="psalm" canonical="true">
<verse sID="Ps.9.1" osisID="Ps.9.1" n="1" />Кіроўцу хору. Пасьля сьмерці Лабэна. Псальма Давідава.</title>
<title type="acrostic"></title>
Алэф
<verse eID="Ps.9.1" />
<lg>
<l level="1">
<verse sID="Ps.9.2" osisID="Ps.9.2" n="2" />Славіць буду <transChange type="added">Цябе </transChange> , Госпадзе, усім сэрцам маім, абвяшчаць пра ўсе цуды Твае, <verse eID="Ps.9.2" /></l>
<l level="1">
<verse sID="Ps.9.3" osisID="Ps.9.3" n="3" />я буду радавацца, весяліцца, імя Тваё апяваць, Усявышні.</l>
</lg>
<title type="acrostic"></title>
Бэт
<verse eID="Ps.9.3" />
```

NB. I had since updated my SFM file to make proper use of poetry tags.
[19-psalm.txt.usfm.zip](https://github.com/adyeths/u2o/files/2873277/19-psalm.txt.usfm.zip)

**Comment by DavidHaslam** [comment]
**Aside:** Of course, the fact that the XML _passes_ **Syntax Check** and the OSIS _validates_ might have too readily convinced you that the issue #85 had been fully fixed. 

"Necessary but not sufficient" still applies.

**Comment by adyeths** [comment]
The latest fix worked fine. And then you changed the text. I'm not sure exactly what's going on here now but it's something different from what I just fixed in #85.

**Comment by DavidHaslam** [comment]
As I was the one that converted the work to USFM back in 2011 with minor improvements in 2014, I still take an interest in it. 

The SWORD module is also one with orphaned verse tags. 

I thought there’d be a good prospect to improve the module by using `u2o.py`. 

The changes made this afternoon make sense in that using poetry tags is more appropriate than just having one `\p` before each `\v 1 ` of each Psalm. 

Also to use `\d ` before `\v 1 ` is valid USFM when some or all of the Psalm descriptive titles are versified. 

But yes - it’s a different issue.

**Comment by adyeths** [comment]
This is now fixed.

**Comment by DavidHaslam** [comment]
_Thanks!_
