### ISSUE TITLE
u2o.py don't recognize well the marker \fp #11

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#9]
I'm adding notes in the konnym. And I have paragraphs in the note, like that:
`\f + \ft Bamimpani ya Ka­naan vanda... kieleka.
\fp Ngindu ... mpamba-mpamba.
\fp Bo ... 2 Nto 18-19.\f*`

The script doesn't convert well to osis format, I have this result:

`<verse sID="Ps.48.3" osisID="Ps.48.3" n="3"/>Ngumba Sion kele ya kitoko ti ya lukumu. </l>
<l level="2">Yo ke pesa kiese na ntoto mvimba </l>
<l level="2">sambu yo kele ngumba ya kimfumu </l>
<l level="2">ye mbanza ya ntotila ya nene!<note placement="foot"><div type="paragraph">\ft Bamimpani ya ... kieleka. </div><div type="paragraph">Ngindu ya Mbanza ... mpamba-mpamba. </div><div type="paragraph">Bo ke yindula nde... 2 Nto 18-19.</div>/note> <verse eID="Ps.48.3"/></l>`

You can see the \ft marker note recognize (This does not matter I can suppress it) and the marker **note** not well formed: </div>**/note>** this is the most important. The script write </div>**/note>**, but the correct may be `</div></note>`.

**Comment by adyeths** [comment]
Both issues should be fixed now.
