### ISSUE TITLE
unhandled tags \esb \esbe

### ISSUE THREAD

**Issue by refdoc** [adyeths/u2o#92]
These tags I have encountered in a new study bible I am working with. They are in essence an extended note, start and end tag.

**Comment by DavidHaslam** [comment]
These tags are described in USFM 2.4 Reference (under Study Bibles) as a “Side Bar” (start & end).

**Comment by refdoc** [comment]
From 3.0 Documentation


Syntax: | \esb
-- | --
paragraph (extended note)
2.1
Beginning (opening) of the sidebar content section.

**Comment by refdoc** [comment]
`

Syntax: | \esb
-- | --
paragraph (extended note)
2.1
Beginning (opening) of the sidebar content section.

`

**Comment by refdoc** [comment]
https://ubsicap.github.io/usfm/notes_study/sidebars.html

**Comment by DavidHaslam** [comment]
The difficulty facing us is that the OSIS 2.1 Reference has (AFAICT) nothing closely equivalent to such a sidebar. 

It might be useful to define a new div element with type=“sidebar”.

ie. In the CrossWire custom version of the OSIS schéma. 

Until then, it would have to be with type=“x-sidebar”.

The SWORD engine would need to be enhanced in order to make practical use thereof. 

AFAIK, there’s no BibleTech group working to update the official OSIS schéma.

**Comment by adyeths** [comment]
added the sidebar markers.

**Comment by cmahte** [comment]
Sidebars have paragraphs within. They aren't structured as a footnote but
as an embedded inline link to a completely different, non scripture
document. Esb and esbe should only occur as a paragraph, but I've never
referenced it come across an implementation that wasn't my own doing.

If anyone is taking this on, moving the sidebars to the beginning of the
book into the intro, and keep a link to the new point as a cross reference.
That's going to be the best implementation possible given the structure of
the sword platform.

**Comment by refdoc** [comment]
This does not work well yet. \esbe is the closing tag for \esb, but multiple \esbe remain unhandled and \esb becomes closed div tags.

**Comment by adyeths** [comment]
I will have to examine the source file more closely. Even when the sidebar content is removed there are issues with the resulting osis that causes it not to validate. I'm not sure why this is happening. Once I figure that out I should be able to get this working properly.

**Comment by adyeths** [comment]
sidebar content should be handled better now. I had to comment out the code for adding divs to majorsections and sections. It was problematic anyway.  I'm still not sure why it's not validating. I will have to research that more.

**Comment by adyeths** [comment]
This issue should be entirely fixed now.
