### ISSUE TITLE
Bad conversion of \cp and \vp markers

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#93]
Hello,
Currently I'm working on a Myanmar bible, as they use their own numbers, I have to work with the tag cp and vp, however the conversion to osis it seems to me that u2o should rather consider the tag \c and tag \v. Currently these tags are ignored, and it is the tages \cp and \vp that are used.
Ex of text:
```
\c 4
\cp ၄
\p
\p
\v 1 \vp ၁။\vp* ထို့နောက်   ဝိညာဉ်တော်သည်   ယေဇူးကို  စာတန်နတ်ဆိုး၏နှောင့်ယှက်ခြင်း  ခံရစေရန် တောကန္တာရ သို့ခေါ်ဆောင်သွား တော်မူ၏။- 
\v 2 \vp ၂။\vp* ကိုယ်တော်သည်လည်း နေ့လေးဆယ်နှင့် ညလေးဆယ်ပတ်လုံး အစာရှောင် တော်မူပြီးနောက်  ဆာလောင်မွတ်သိပ်နေလေ၏။-  
\v 3 \vp ၃။\vp* ထိုအခါ နှောင့်ယှက်သောသူသည် အထံတော် သို့ချဉ်းကပ်၍ သင်သည် ဘုရား သခင်၏သားတော်မှန် လျှင် ဤကျောက်ခဲများကို ပေါင်မုန့်ဖြစ်စေရန် အမိန့်ရှိ တော်မူပါဟု ကိုယ်တော်အား လျှောက်လေ၏။-  
\v 4 \vp ၄။\vp* သို့ရာတွင်  ကိုယ်တော်က  လူသည်  အစားအစာအားဖြင့်သာ  အသက်ရှင် သည် မဟုတ်၊ ဘုရားသခင်၏နှုတ်တော် ထွက်စကားရှိ သမျှဖြင့်လည်း အသက်ရှင်ရကြောင်းကို ကျမ်းစာတော်မြတ်၌ ရေးထားသည်ဟု ဖြေကြားတော် မူ၏။
\v 5 \vp ၅။\vp* ထိုအခါ နတ်ဆိုးသည် ကိုယ်တော်အား သန့်ရှင်း သောမြို့တော်သို့ ခေါ်ဆောင်သွားပြီးလျှင် ဗိမာန်တော်၏အထွတ်၌ ထားလျက်၊- 
```
Result:
```
<chapter sID="Matt.၄" osisID="Matt.၄" n="၄" />
<verse eID="Matt.၄.၁၇။" />
</p>
<p>
<verse sID="Matt.၄.၁။" osisID="Matt.၄.၁။" n="၁။" />ထို့နောက် ဝိညာဉ်တော်သည် ယေဇူးကို စာတန်နတ်ဆိုး၏နှောင့်ယှက်ခြင်း ခံရစေရန် တောကန္တာရ သို့ခေါ်ဆောင်သွား တော်မူ၏။-
<verse eID="Matt.၄.၁။" />
<verse sID="Matt.၄.၂။" osisID="Matt.၄.၂။" n="၂။" />ကိုယ်တော်သည်လည်း နေ့လေးဆယ်နှင့် ညလေးဆယ်ပတ်လုံး အစာရှောင် တော်မူပြီးနောက် ဆာလောင်မွတ်သိပ်နေလေ၏။-
<verse eID="Matt.၄.၂။" />
<verse sID="Matt.၄.၃။" osisID="Matt.၄.၃။" n="၃။" />ထိုအခါ နှောင့်ယှက်သောသူသည် အထံတော် သို့ချဉ်းကပ်၍ သင်သည် ဘုရား သခင်၏သားတော်မှန် လျှင် ဤကျောက်ခဲများကို ပေါင်မုန့်ဖြစ်စေရန် အမိန့်ရှိ တော်မူပါဟု ကိုယ်တော်အား လျှောက်လေ၏။-
<verse eID="Matt.၄.၃။" />
```
Should not cp and vp be ignored? 
Thanks for help.

**Comment by cmahte** [comment]
I suggest this be a flag in the converter.

u2o -v=v to follow the marked verses (default)
u2o -v=vp to follow the published verses.
u20 -v=va to follow the alternate verses.

u2o -c=c to follow the marked chapter number.
u20 -c=cp to follow the published chapter names. (note cp is usually
non-numeric)
u20 -c=ca to follow the alternate chapter names.

**Comment by adyeths** [comment]
u2o should now convert \cp and \vp tags to milestones like it does for \ca and \va tags. This is the best way I know how to handle these tags at this time when converting to osis.

**Comment by LAfricain** [comment]
> u2o should now convert \cp and \vp tags to milestones like it does for \ca and \va tags

It Okay for me. Let me now if you propose a solution.

**Comment by adyeths** [comment]
I changed the handling of \cp and \vp tags again. I now put the value of them in the n attribute of the chapter and verse tags since that appears to be a better alternative than inserting them as separate milestone markers.

**Comment by DavidHaslam** [comment]
Does this test OK for a verse range?

**Comment by LAfricain** [comment]
Thank you very much, It works well.
