### ISSUE TITLE
\cp conversion remove a part of the content

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#95]
If I have a \cp tag like that:
`\cp Psaume 42 (Vulg. XLI)`
In the Osis file I get `42 (Vulg. XLI)` the word Psaume is removed.
What is expected is ` Psaume 42 (Vulg. XLI)`

**Comment by adyeths** [comment]
That doesn't look like a correct usage of the \cp tag to me.

**Comment by LAfricain** [comment]
You are right! It probably the cl tag the good one.

**Comment by cmahte** [comment]
Correctly stated in USFM

\c 42
\cl Psaume 42 \ca Vulg. XLI \ca*

(but I include the parenthesis myself, since some languages prefer
different markups.)
