### ISSUE TITLE
Nesting errors when list (\li) paragraph starts midverse

### ISSUE THREAD

**Issue by cmahte** [adyeths/u2o#97]
u2o following by OSIS2Mod gives a long string of nesting errors for [English Unlocked Dynamic Bible](https://github.com/BeTheLight/ENG-B-UDB2019-cc-PSFM)

[SwordModBuildErrors.txt](https://github.com/adyeths/u2o/files/3636599/SwordModBuildErrors.txt)

I don't see anything unusual in the USFM... I don't understand enough about what the OSIS should look like... 

All the link messages I THINK are combined verses., but I haven't verified.) I've only looked at the first few NESTING warnings, but these seem to point at the tag \li as the culprit. Its use is correct in the document as far as I know.

**Comment by adyeths** [comment]
There are situations where it will be impossible to eliminate the warnings like this that are reported by the osis2mod utility. This is one of those situations. The osis is still valid, so this isn't a bug in u2o. It's just an annoying message being reported by the sword projects osis2mod utility.

The link messages are exactly what you thought, combined verses. Just information, not a report of an error.
