### ISSUE TITLE
Old style (pre-3.0) figure markup handling

### ISSUE THREAD

**Issue by mmartin9684-sil** [adyeths/u2o#99]
Figures that use the pre-USFM 3.0 figure markup, with order-based figure attributes (i.e., "\fig DESC|FILE|SIZE|LOC|COPY|CAP\REF\fig*") result in an exception.  The exception is raised in 'figtags', line 2225:
                        fig[0] = {
                            True: "\n".format(fig[0]),
                            False: fig[0],
                        }**[fig[0]]**

**Comment by adyeths** [comment]
This should be fixed now.

**Comment by mmartin9684-sil** [comment]
Awesome!
